//region IterproUserPermission

export type IterproUserPermission =
	| 'administration'
	| 'assessments'
	| 'attendances'
	| 'bonus'
	| 'cash-flow'
	| 'compare-players'
	| 'cost-items'
	| 'drills'
	| 'examination'
	| 'finance-overview'
	| 'fitness'
	| 'game-stats'
	| 'import-data'
	| 'infirmary'
	| 'legal'
	| 'legal-admin'
	| 'maintenance'
	| 'manager'
	| 'medical'
	| 'medical-statistics'
	| 'medical-test-analysis'
	| 'my-team'
	| 'notarize'
	| 'notifyContract'
	| 'overview'
	| 'performance'
	| 'planning'
	| 'players'
	| 'profile-attributes'
	| 'readiness'
	| 'robustness'
	| 'scouting'
	| 'scouting-games'
	| 'scouting-games-report'
	| 'session-analysis'
	| 'settings'
	| 'squads'
	| 'tactics'
	| 'test-analysis'
	| 'thresholds'
	| 'transfers'
	| 'video-gallery'
	| 'workload-analysis';

//endregion
