export function contractFieldToLabel(contractField: string): string {
	switch (contractField) {
		case 'basicWage':
		case 'fee':
			return 'admin.contracts.basicWage';
		case 'appearanceFee':
			return 'admin.contracts.appearanceFees';
		case 'appearance':
			return 'admin.contracts.appearance';
		case 'performanceFee':
			return 'admin.contracts.performanceFee';
		case 'performance':
			return 'admin.contracts.performance';
		case 'standardTeam':
			return 'admin.contracts.standardTeam';
		case 'signing':
			return 'admin.contracts.signing';
		case 'custom':
			return 'admin.contracts.custom';
		case 'contribution':
			return 'admin.contracts.contributions';
		case 'buyout':
			return 'admin.contracts.buyout';
		case 'buyBack':
			return 'admin.contracts.options.buyBack';
		case 'privateWriting':
			return 'admin.contracts.privateWriting';
		case 'insurance':
			return 'admin.contracts.insurance';
		case 'dateFrom':
		case 'duration_from':
			return 'admin.contracts.from';
		case 'dateTo':
		case 'duration_to':
		case 'endDate':
			return 'admin.contracts.to';
		case 'additionalClauses':
			return 'admin.contracts.additionalClauses';
		case 'contractType':
		case 'type':
			return 'admin.contracts.contractType';
		case 'signature':
			return 'admin.contracts.signature';
		case 'variableWagePart':
			return 'admin.contracts.variableWagePart';
		case 'bonusCap':
			return 'admin.contracts.bonusCap';
		case 'notes':
			return 'admin.contracts.notes';
		case 'agent':
			return 'admin.contracts.agent';
		case 'benefits':
			return 'admin.contracts.benefits';
		case 'options':
			return 'admin.contracts.options';
		case 'commercialRights':
			return 'admin.contracts.commercialRights';
		case 'conflict':
			return 'admin.contracts.agent.conflict';
		case 'ictDate':
			return 'admin.contracts.itcDate';
		case 'homeTransfer':
			return 'admin.contracts.homeTransfer';
		case 'renew':
			return 'admin.contracts.renew';
		case 'stipulationDate':
		case 'duration_stipulation':
			return 'admin.contracts.stipulationDate';
		case 'on':
			return 'admin.contracts.on';
		case 'amount':
			return 'profile.archive.amount';
		case 'grossAmount':
			return 'admin.contracts.grossAmount';
		case 'loanOption':
			return 'admin.contracts.loanOption';
		case 'valorization':
			return 'admin.contracts.valorization';
		case '_attachments':
			return 'test.attachments';
		case 'sellOnFee':
			return 'admin.contracts.options.sellOnFee';
		case 'club':
			return 'admin.club';
		case 'fromClub':
			return 'admin.contracts.fromClub';
		case 'agentContract':
			return 'admin.contracts.agentOptions';
		default:
			console.warn('Unknown contract field: ' + contractField);
			return contractField;
	}
}
