export default {
	InStat: {
		rawMetrics: [
			{ name: "TEAM", label: "TEAM", type: "number" },
			{ name: "MATCH", label: "MATCH", type: "number" },
			{ name: "MATCH DATE", label: "MATCH DATE", type: "number" },
			{ name: "AVERAGE INSTAT INDEX", label: "AVERAGE INSTAT INDEX", type: "number" },
			{ name: "GOALS SCORED - RESULT", label: "GOALS SCORED - RESULT", type: "number" },
			{ name: "GOALS CONCEDED - RESULT", label: "GOALS CONCEDED - RESULT", type: "number" },
			{ name: "YELLOW CARD", label: "YELLOW CARD", type: "number" },
			{ name: "RED CARD", label: "RED CARD", type: "number" },
			{ name: "CORNERS", label: "CORNERS", type: "number" },
			{ name: "OFFSIDES", label: "OFFSIDES", type: "number" },
			{ name: "FOULS", label: "FOULS", type: "number" },
			{ name: "FOULS - OPPONENT", label: "FOULS - OPPONENT", type: "number" },
			{ name: "BALL POSSESSION, MIN", label: "BALL POSSESSION, MIN", type: "number" },
			{ name: "BALL POSSESSION IN OWN HALF", label: "BALL POSSESSION IN OWN HALF", type: "number" },
			{ name: "BALL POSSESSION IN OPP_ HALF", label: "BALL POSSESSION IN OPP_ HALF", type: "number" },
			{ name: "BALL POSSESSION TIME IN THE FINAL THIRD OF THE FIELD", label: "BALL POSSESSION TIME IN THE FINAL THIRD OF THE FIELD", type: "number" },
			{ name: "SHOTS", label: "SHOTS", type: "number" },
			{ name: "SHOTS ON TARGET", label: "SHOTS ON TARGET", type: "number" },
			{ name: "ATTACKS", label: "ATTACKS", type: "number" },
			{ name: "POSITIONAL ATTACKS", label: "POSITIONAL ATTACKS", type: "number" },
			{ name: "ATTACKS WITH SHOTS - POSITIONAL", label: "ATTACKS WITH SHOTS - POSITIONAL", type: "number" },
			{ name: "ATTACKS WITH SHOTS - POSITIONAL ATTACKS, %", label: "ATTACKS WITH SHOTS - POSITIONAL ATTACKS, %", type: "number" },
			{ name: "COUNTER-ATTACKS", label: "COUNTER-ATTACKS", type: "number" },
			{ name: "COUNTER-ATTACKS WITH A SHOT", label: "COUNTER-ATTACKS WITH A SHOT", type: "number" },
			{ name: "ATTACKS WITH SHOTS - COUNTER-ATTACKS, %", label: "ATTACKS WITH SHOTS - COUNTER-ATTACKS, %", type: "number" },
			{ name: "SET PIECES ATTACK", label: "SET PIECES ATTACK", type: "number" },
			{ name: "ATTACKS WITH SHOTS - SET PIECES ATTACKS", label: "ATTACKS WITH SHOTS - SET PIECES ATTACKS", type: "number" },
			{ name: "ATTACKS WITH SHOTS - SET PIECES ATTACKS, %", label: "ATTACKS WITH SHOTS - SET PIECES ATTACKS, %", type: "number" },
			{ name: "PASSES", label: "PASSES", type: "number" },
			{ name: "PASSES ACCURATE", label: "PASSES ACCURATE", type: "number" },
			{ name: "% OF ACCURATE PASSES", label: "% OF ACCURATE PASSES", type: "number" },
			{ name: "EXTRA ATTACKING AND KEY PASSES", label: "EXTRA ATTACKING AND KEY PASSES", type: "number" },
			{ name: "EXTRA ATTACKING AND KEY PASSES - ACCURATE", label: "EXTRA ATTACKING AND KEY PASSES - ACCURATE", type: "number" },
			{ name: "CROSSES", label: "CROSSES", type: "number" },
			{ name: "CROSSES ACCURATE", label: "CROSSES ACCURATE", type: "number" },
			{ name: "CROSSES - ACCURATE, %", label: "CROSSES - ACCURATE, %", type: "number" },
			{ name: "CHALLENGES", label: "CHALLENGES", type: "number" },
			{ name: "CHALLENGES WON", label: "CHALLENGES WON", type: "number" },
			{ name: "CHALLENGES WON, %", label: "CHALLENGES WON, %", type: "number" },
			{ name: "DEFENSIVE CHALLENGES", label: "DEFENSIVE CHALLENGES", type: "number" },
			{ name: "CHALLENGES IN DEFENCE / WON", label: "CHALLENGES IN DEFENCE / WON", type: "number" },
			{ name: "CHALLENGES IN DEFENCE / WON, %", label: "CHALLENGES IN DEFENCE / WON, %", type: "number" },
			{ name: "ATTACKING CHALLENGES", label: "ATTACKING CHALLENGES", type: "number" },
			{ name: "CHALLENGES IN ATTACK / WON", label: "CHALLENGES IN ATTACK / WON", type: "number" },
			{ name: "CHALLENGES IN ATTACK / WON, %", label: "CHALLENGES IN ATTACK / WON, %", type: "number" },
			{ name: "AIR CHALLENGES", label: "AIR CHALLENGES", type: "number" },
			{ name: "AIR CHALLENGES WON", label: "AIR CHALLENGES WON", type: "number" },
			{ name: "AIR CHALLENGES, %", label: "AIR CHALLENGES, %", type: "number" },
			{ name: "DRIBBLES", label: "DRIBBLES", type: "number" },
			{ name: "DRIBBLES SUCCESSFUL", label: "DRIBBLES SUCCESSFUL", type: "number" },
			{ name: "DRIBBLES %", label: "DRIBBLES %", type: "number" },
			{ name: "TACKLES", label: "TACKLES", type: "number" },
			{ name: "TACKLES SUCCESSFUL", label: "TACKLES SUCCESSFUL", type: "number" },
			{ name: "TACKLES %", label: "TACKLES %", type: "number" },
			{ name: "INTERCEPTIONS", label: "INTERCEPTIONS", type: "number" },
			{ name: "INTERCEPTIONS / IN OPP_ HALF", label: "INTERCEPTIONS / IN OPP_ HALF", type: "number" },
			{ name: "PICKING UP FREE BALLS", label: "PICKING UP FREE BALLS", type: "number" },
			{ name: "PICKING UP FREE BALLS - IN OPP_ HALF", label: "PICKING UP FREE BALLS - IN OPP_ HALF", type: "number" },
			{ name: "LOST BALLS", label: "LOST BALLS", type: "number" },
			{ name: "LOST BALLS / IN OWN HALF", label: "LOST BALLS / IN OWN HALF", type: "number" },
			{ name: "RECOVERED BALLS", label: "RECOVERED BALLS", type: "number" },
			{ name: "RECOVERED BALLS / IN OPP_ HALF", label: "RECOVERED BALLS / IN OPP_ HALF", type: "number" },
			{ name: "PASSES FORWARD (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES FORWARD (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES BACK (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES BACK (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE LEFT (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE LEFT (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE RIGHT (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE RIGHT (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES FORWARD ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES FORWARD ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES BACK ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES BACK ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE LEFT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE LEFT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE RIGHT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE RIGHT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" }
		],
		goalsScoredField: "GOALS SCORED - RESULT",
		goalsConcedField: "GOALS CONCEDED - RESULT"
	},
	PaniniDigital: {
		rawMetrics: [
			{ name: "Minuti di gioco", label: "Minuti di gioco", type: "number" },
			{ name: "Tempo effettivo", label: "Tempo effettivo", type: "number" },
			{ name: "Palle giocate", label: "Palle giocate", type: "number" },
			{ name: "Palle giocate nella metà campo avversaria", label: "Palle giocate nella metà campo avversaria", type: "number" },
			{ name: "% palle giocate nella metà campo avversaria", label: "% palle giocate nella metà campo avversaria", type: "number" },
			{ name: "Possesso palla", label: "Possesso palla", type: "number" },
			{ name: "% media di possesso palla", label: "% media di possesso palla", type: "number" },
			{ name: "Supremazia territoriale", label: "Supremazia territoriale", type: "number" },
			{ name: "Velocità di gioco", label: "Velocità di gioco", type: "number" },
			{ name: "IVS generale", label: "IVS generale", type: "number" },
			{ name: "IVS difesa", label: "IVS difesa", type: "number" },
			{ name: "IVS attacco", label: "IVS attacco", type: "number" },
			{ name: "Passaggi tentati", label: "Passaggi tentati", type: "number" },
			{ name: "Passaggi riusciti", label: "Passaggi riusciti", type: "number" },
			{ name: "% passaggi riusciti", label: "% passaggi riusciti", type: "number" },
			{ name: "% passaggi riusciti in avanti", label: "% passaggi riusciti in avanti", type: "number" },
			{ name: "% passaggi riusciti laterali", label: "% passaggi riusciti laterali", type: "number" },
			{ name: "% passaggi riusciti indietro", label: "% passaggi riusciti indietro", type: "number" },
			{ name: "Passaggi riusciti in difesa", label: "Passaggi riusciti in difesa", type: "number" },
			{ name: "Passaggi riusciti a centrocampo", label: "Passaggi riusciti a centrocampo", type: "number" },
			{ name: "Passaggi riusciti in attacco", label: "Passaggi riusciti in attacco", type: "number" },
			{ name: "Passaggi alti utili", label: "Passaggi alti utili", type: "number" },
			{ name: "Passaggi bassi utili", label: "Passaggi bassi utili", type: "number" },
			{ name: "Passaggi bassi nella metà campo avversaria", label: "Passaggi bassi nella metà campo avversaria", type: "number" },
			{ name: "passaggi bassi utili nella metà campo avversaria", label: "passaggi bassi utili nella metà campo avversaria", type: "number" },
			{ name: "Giocate utili", label: "Giocate utili", type: "number" },
			{ name: "% giocate utili", label: "% giocate utili", type: "number" },
			{ name: "Giocate utili nella metà campo avversaria", label: "Giocate utili nella metà campo avversaria", type: "number" },
			{ name: "% giocate utili nella metà campo avversaria", label: "% giocate utili nella metà campo avversaria", type: "number" },
			{ name: "Giocate utili in difesa", label: "Giocate utili in difesa", type: "number" },
			{ name: "Giocate utili a centrocampo", label: "Giocate utili a centrocampo", type: "number" },
			{ name: "Giocate utili in attacco", label: "Giocate utili in attacco", type: "number" },
			{ name: "Colpi di testa", label: "Colpi di testa", type: "number" },
			{ name: "Colpi di testa in area avversaria", label: "Colpi di testa in area avversaria", type: "number" },
			{ name: "% palle giocate sulla fascia destra", label: "% palle giocate sulla fascia destra", type: "number" },
			{ name: "% palle giocate sulla fascia centrale", label: "% palle giocate sulla fascia centrale", type: "number" },
			{ name: "% palle giocate sulla fascia sinistra", label: "% palle giocate sulla fascia sinistra", type: "number" },
			{ name: "% palle giocate in difesa", label: "% palle giocate in difesa", type: "number" },
			{ name: "% palle giocate a centrocampo", label: "% palle giocate a centrocampo", type: "number" },
			{ name: "% palle giocate in attacco", label: "% palle giocate in attacco", type: "number" },
			{ name: "Misura della squadra", label: "Misura della squadra", type: "number" },
			{ name: "Baricentro (mt)", label: "Baricentro (mt)", type: "number" },
			{ name: "Pressing (mt)", label: "Pressing (mt)", type: "number" },
			{ name: "Pali", label: "Pali", type: "number" },
			{ name: "Reti", label: "Reti", type: "number" },
			{ name: "Distanza reti (mt)", label: "Distanza reti (mt)", type: "number" },
			{ name: "Reti da meno di 8 mt", label: "Reti da meno di 8 mt", type: "number" },
			{ name: "Reti da 8 a 16 mt", label: "Reti da 8 a 16 mt", type: "number" },
			{ name: "Reti da oltre 16 mt", label: "Reti da oltre 16 mt", type: "number" },
			{ name: "Autoreti", label: "Autoreti", type: "number" },
			{ name: "Sostituito", label: "Sostituito", type: "number" },
			{ name: "Subentrato", label: "Subentrato", type: "number" },
			{ name: "Ammonizioni", label: "Ammonizioni", type: "number" },
			{ name: "Espulsioni", label: "Espulsioni", type: "number" },
			{ name: "Espulsioni dirette", label: "Espulsioni dirette", type: "number" },
			{ name: "Espulsioni per doppia ammonizione", label: "Espulsioni per doppia ammonizione", type: "number" },
			{ name: "IVP", label: "IVP", type: "number" },
			{ name: "Reti subite", label: "Reti subite", type: "number" },
			{ name: "% reti subite", label: "% reti subite", type: "number" },
			{ name: "Distanza reti subite (mt)", label: "Distanza reti subite (mt)", type: "number" },
			{ name: "Reti subite da meno di 8 mt", label: "Reti subite da meno di 8 mt", type: "number" },
			{ name: "Reti subite da 8 a 16 mt", label: "Reti subite da 8 a 16 mt", type: "number" },
			{ name: "Reti subite da oltre 16 mt", label: "Reti subite da oltre 16 mt", type: "number" },
			{ name: "Reti subite direttamente su calcio piazzato", label: "Reti subite direttamente su calcio piazzato", type: "number" },
			{ name: "Reti subite indirettamente su calcio piazzato", label: "Reti subite indirettamente su calcio piazzato", type: "number" },
			{ name: "Autoreti subite", label: "Autoreti subite", type: "number" },
			{ name: "Rigori subiti", label: "Rigori subiti", type: "number" },
			{ name: "Reti subite su rigore", label: "Reti subite su rigore", type: "number" },
			{ name: "Reti totali subite su calcio piazzato", label: "Reti totali subite su calcio piazzato", type: "number" },
			{ name: "Tiri subìti", label: "Tiri subìti", type: "number" },
			{ name: "Distanza tiri subiti (mt)", label: "Distanza tiri subiti (mt)", type: "number" },
			{ name: "Tiri dentro subìti", label: "Tiri dentro subìti", type: "number" },
			{ name: "Distanza tiri dentro subiti (mt)", label: "Distanza tiri dentro subiti (mt)", type: "number" },
			{ name: "Tiri dentro subiti da meno di 8 mt", label: "Tiri dentro subiti da meno di 8 mt", type: "number" },
			{ name: "Tiri dentro subiti da 8 a 16 mt", label: "Tiri dentro subiti da 8 a 16 mt", type: "number" },
			{ name: "Tiri dentro subiti da oltre 16 mt", label: "Tiri dentro subiti da oltre 16 mt", type: "number" },
			{ name: "Tiri subiti ribattuti o deviati", label: "Tiri subiti ribattuti o deviati", type: "number" },
			{ name: "Parate", label: "Parate", type: "number" },
			{ name: "Parate su tiri da dentro area", label: "Parate su tiri da dentro area", type: "number" },
			{ name: "Parate su tiri da fuori area", label: "Parate su tiri da fuori area", type: "number" },
			{ name: "Parate su occasione", label: "Parate su occasione", type: "number" },
			{ name: "Parate su rigore", label: "Parate su rigore", type: "number" },
			{ name: "Uscite", label: "Uscite", type: "number" },
			{ name: "Uscite alte", label: "Uscite alte", type: "number" },
			{ name: "Uscite basse", label: "Uscite basse", type: "number" },
			{ name: "Rinvii del portiere", label: "Rinvii del portiere", type: "number" },
			{ name: "Rinvii utili del portiere", label: "Rinvii utili del portiere", type: "number" },
			{ name: "Rilanci lunghi utili", label: "Rilanci lunghi utili", type: "number" },
			{ name: "Rilanci lunghi", label: "Rilanci lunghi", type: "number" },
			{ name: "% protezione area", label: "% protezione area", type: "number" },
			{ name: "% protezione aerea dell'area", label: "% protezione aerea dell'area", type: "number" },
			{ name: "Rinvii", label: "Rinvii", type: "number" },
			{ name: "Rinvii utili", label: "Rinvii utili", type: "number" },
			{ name: "Palle recuperate", label: "Palle recuperate", type: "number" },
			{ name: "Recuperi in difesa", label: "Recuperi in difesa", type: "number" },
			{ name: "Recuperi a centrocampo", label: "Recuperi a centrocampo", type: "number" },
			{ name: "Recuperi in attacco", label: "Recuperi in attacco", type: "number" },
			{ name: "Palle recuperate effettive", label: "Palle recuperate effettive", type: "number" },
			{ name: "% recuperi effettivi/PG avversari", label: "% recuperi effettivi/PG avversari", type: "number" },
			{ name: "Palle riconquistate", label: "Palle riconquistate", type: "number" },
			{ name: "% per fine azione avversaria", label: "% per fine azione avversaria", type: "number" },
			{ name: "% recuperi effettivi", label: "% recuperi effettivi", type: "number" },
			{ name: "% recuperi temporanei", label: "% recuperi temporanei", type: "number" },
			{ name: "Recuperi in zona area", label: "Recuperi in zona area", type: "number" },
			{ name: "Recuperi effettivi in attacco", label: "Recuperi effettivi in attacco", type: "number" },
			{ name: "Intercettazioni", label: "Intercettazioni", type: "number" },
			{ name: "Intercettazioni effettive", label: "Intercettazioni effettive", type: "number" },
			{ name: "Anticipi", label: "Anticipi", type: "number" },
			{ name: "Anticipi effettivi", label: "Anticipi effettivi", type: "number" },
			{ name: "Anticipi di testa", label: "Anticipi di testa", type: "number" },
			{ name: "Contrasti", label: "Contrasti", type: "number" },
			{ name: "Contrasti effettivi", label: "Contrasti effettivi", type: "number" },
			{ name: "Recuperi in elevazione", label: "Recuperi in elevazione", type: "number" },
			{ name: "Recuperi in elevazione effettivi", label: "Recuperi in elevazione effettivi", type: "number" },
			{ name: "Recuperi aerei", label: "Recuperi aerei", type: "number" },
			{ name: "Recuperi aerei in area", label: "Recuperi aerei in area", type: "number" },
			{ name: "Duelli aerei", label: "Duelli aerei", type: "number" },
			{ name: "Duelli aerei vinti", label: "Duelli aerei vinti", type: "number" },
			{ name: "% duelli aerei vinti", label: "% duelli aerei vinti", type: "number" },
			{ name: "Duelli aerei persi", label: "Duelli aerei persi", type: "number" },
			{ name: "% duelli aerei persi", label: "% duelli aerei persi", type: "number" },
			{ name: "Raddoppi", label: "Raddoppi", type: "number" },
			{ name: "Raddoppi effettivi", label: "Raddoppi effettivi", type: "number" },
			{ name: "Palle perse", label: "Palle perse", type: "number" },
			{ name: "Palle perse", label: "Palle perse", type: "number" },
			{ name: "Palle perse in difesa", label: "Palle perse in difesa", type: "number" },
			{ name: "Palle perse a centrocampo", label: "Palle perse a centrocampo", type: "number" },
			{ name: "Palle perse in attacco", label: "Palle perse in attacco", type: "number" },
			{ name: "Palle perse effettive", label: "Palle perse effettive", type: "number" },
			{ name: "% palle perse effettive", label: "% palle perse effettive", type: "number" },
			{ name: "Palle perse effetive in difesa", label: "Palle perse effetive in difesa", type: "number" },
			{ name: "Palle perse effettive a centrocampo", label: "Palle perse effettive a centrocampo", type: "number" },
			{ name: "Palle perse effettive in attacco", label: "Palle perse effettive in attacco", type: "number" },
			{ name: "Falli commessi", label: "Falli commessi", type: "number" },
			{ name: "Falli commessi nei pressi della propria area", label: "Falli commessi nei pressi della propria area", type: "number" },
			{ name: "Falli di mano", label: "Falli di mano", type: "number" },
			{ name: "Poss_ palla avv_/Falli contro", label: "Poss_ palla avv_/Falli contro", type: "number" },
			{ name: "Falli contro/Ammonizioni", label: "Falli contro/Ammonizioni", type: "number" },
			{ name: "Falli contro/Espulsioni", label: "Falli contro/Espulsioni", type: "number" },
			{ name: "Giocate in area dagli avv_/Rigori contro", label: "Giocate in area dagli avv_/Rigori contro", type: "number" },
			{ name: "Fuorigioco avversari", label: "Fuorigioco avversari", type: "number" },
			{ name: "Fuorigioco", label: "Fuorigioco", type: "number" },
			{ name: "% palle a scavalcare il centrocampo", label: "% palle a scavalcare il centrocampo", type: "number" },
			{ name: "% azioni manovrate da dietro", label: "% azioni manovrate da dietro", type: "number" },
			{ name: "Cambi di gioco", label: "Cambi di gioco", type: "number" },
			{ name: "Ripartenze", label: "Ripartenze", type: "number" },
			{ name: "Passaggi di testa", label: "Passaggi di testa", type: "number" },
			{ name: "Passaggi di testa utili", label: "Passaggi di testa utili", type: "number" },
			{ name: "Passaggi lunghi", label: "Passaggi lunghi", type: "number" },
			{ name: "Passaggi lunghi utili", label: "Passaggi lunghi utili", type: "number" },
			{ name: "% passaggi lunghi utili", label: "% passaggi lunghi utili", type: "number" },
			{ name: "Pallonetti", label: "Pallonetti", type: "number" },
			{ name: "Pallonetti utili", label: "Pallonetti utili", type: "number" },
			{ name: "% pallonetti utili", label: "% pallonetti utili", type: "number" },
			{ name: "Passaggi filtranti", label: "Passaggi filtranti", type: "number" },
			{ name: "Passaggi filtranti utili", label: "Passaggi filtranti utili", type: "number" },
			{ name: "% passaggi filtranti utili", label: "% passaggi filtranti utili", type: "number" },
			{ name: "Sovrapposizioni", label: "Sovrapposizioni", type: "number" },
			{ name: "Cross", label: "Cross", type: "number" },
			{ name: "Cross utili", label: "Cross utili", type: "number" },
			{ name: "% cross utili", label: "% cross utili", type: "number" },
			{ name: "Cross su azione da destra", label: "Cross su azione da destra", type: "number" },
			{ name: "% cross su azione da destra", label: "% cross su azione da destra", type: "number" },
			{ name: "Cross su azione da sinistra", label: "Cross su azione da sinistra", type: "number" },
			{ name: "% cross su azione da sinistra", label: "% cross su azione da sinistra", type: "number" },
			{ name: "Cross su azione", label: "Cross su azione", type: "number" },
			{ name: "Cross su azione utili", label: "Cross su azione utili", type: "number" },
			{ name: "Cross su azione dai 35 ai 18 mt", label: "Cross su azione dai 35 ai 18 mt", type: "number" },
			{ name: "Cross su azione dal fondo", label: "Cross su azione dal fondo", type: "number" },
			{ name: "Cross su azione dal fondo utili", label: "Cross su azione dal fondo utili", type: "number" },
			{ name: "Cross su calcio piazzato", label: "Cross su calcio piazzato", type: "number" },
			{ name: "Passaggi lungo linea", label: "Passaggi lungo linea", type: "number" },
			{ name: "Passaggi lungo linea utili", label: "Passaggi lungo linea utili", type: "number" },
			{ name: "% passaggi lungo linea utili", label: "% passaggi lungo linea utili", type: "number" },
			{ name: "Dai e vai", label: "Dai e vai", type: "number" },
			{ name: "Accelerazioni", label: "Accelerazioni", type: "number" },
			{ name: "Colpi di testa offensivi", label: "Colpi di testa offensivi", type: "number" },
			{ name: "Sponde", label: "Sponde", type: "number" },
			{ name: "Veli", label: "Veli", type: "number" },
			{ name: "Tagli dentro", label: "Tagli dentro", type: "number" },
			{ name: "Tagli fuori", label: "Tagli fuori", type: "number" },
			{ name: "Allargamenti", label: "Allargamenti", type: "number" },
			{ name: "Dribbling", label: "Dribbling", type: "number" },
			{ name: "Dribbling utili", label: "Dribbling utili", type: "number" },
			{ name: "% dribbling utili", label: "% dribbling utili", type: "number" },
			{ name: "Dribbling persi", label: "Dribbling persi", type: "number" },
			{ name: "Simulazioni", label: "Simulazioni", type: "number" },
			{ name: "Colpi di tacco", label: "Colpi di tacco", type: "number" },
			{ name: "Azioni in rovesciata", label: "Azioni in rovesciata", type: "number" },
			{ name: "Falli subiti", label: "Falli subiti", type: "number" },
			{ name: "Possesso palla/Falli a favore", label: "Possesso palla/Falli a favore", type: "number" },
			{ name: "Giocate in area avv_/Rigori a favore", label: "Giocate in area avv_/Rigori a favore", type: "number" },
			{ name: "Assist", label: "Assist", type: "number" },
			{ name: "Assist su sviluppo di azione", label: "Assist su sviluppo di azione", type: "number" },
			{ name: "Assist su sviluppo di calcio piazzato", label: "Assist su sviluppo di calcio piazzato", type: "number" },
			{ name: "Assist vincenti", label: "Assist vincenti", type: "number" },
			{ name: "Assist vincenti su sviluppo di azione", label: "Assist vincenti su sviluppo di azione", type: "number" },
			{ name: "Assist vincenti su sviluppo di calcio piazzato", label: "Assist vincenti su sviluppo di calcio piazzato", type: "number" },
			{ name: "% attacco alla porta", label: "% attacco alla porta", type: "number" },
			{ name: "% attacco aereo alla porta", label: "% attacco aereo alla porta", type: "number" },
			{ name: "Occasioni", label: "Occasioni", type: "number" },
			{ name: "% occasioni sfruttate", label: "% occasioni sfruttate", type: "number" },
			{ name: "Occasioni su azione", label: "Occasioni su azione", type: "number" },
			{ name: "Occasioni su calcio piazzato", label: "Occasioni su calcio piazzato", type: "number" },
			{ name: "Occasioni dirette su calcio piazzato", label: "Occasioni dirette su calcio piazzato", type: "number" },
			{ name: "Occasioni dirette da angolo", label: "Occasioni dirette da angolo", type: "number" },
			{ name: "Occasioni dirette da punizione in attacco", label: "Occasioni dirette da punizione in attacco", type: "number" },
			{ name: "Occasioni indirette su calcio piazzato", label: "Occasioni indirette su calcio piazzato", type: "number" },
			{ name: "Occasioni indirette da angolo", label: "Occasioni indirette da angolo", type: "number" },
			{ name: "Occasioni indirette da punizione in attacco", label: "Occasioni indirette da punizione in attacco", type: "number" },
			{ name: "Occasioni indirette da laterale in attacco", label: "Occasioni indirette da laterale in attacco", type: "number" },
			{ name: "Tiri", label: "Tiri", type: "number" },
			{ name: "Capacità realizzativa", label: "Capacità realizzativa", type: "number" },
			{ name: "Distanza tiri (mt)", label: "Distanza tiri (mt)", type: "number" },
			{ name: "Precisione nel tiro", label: "Precisione nel tiro", type: "number" },
			{ name: "Tiri dentro", label: "Tiri dentro", type: "number" },
			{ name: "Distanza tiri dentro (mt)", label: "Distanza tiri dentro (mt)", type: "number" },
			{ name: "Tiri dentro da meno di 8 mt", label: "Tiri dentro da meno di 8 mt", type: "number" },
			{ name: "Tiri dentro da 8 a 16 mt", label: "Tiri dentro da 8 a 16 mt", type: "number" },
			{ name: "Tiri dentro da oltre 16 mt", label: "Tiri dentro da oltre 16 mt", type: "number" },
			{ name: "Tiri dentro di destro", label: "Tiri dentro di destro", type: "number" },
			{ name: "Tiri dentro di sinistro", label: "Tiri dentro di sinistro", type: "number" },
			{ name: "Tiri dentro di testa", label: "Tiri dentro di testa", type: "number" },
			{ name: "Tiri fuori", label: "Tiri fuori", type: "number" },
			{ name: "Distanza tiri fuori (mt)", label: "Distanza tiri fuori (mt)", type: "number" },
			{ name: "Tiri di destro", label: "Tiri di destro", type: "number" },
			{ name: "Tiri di sinistro", label: "Tiri di sinistro", type: "number" },
			{ name: "Tiri di testa", label: "Tiri di testa", type: "number" },
			{ name: "Tiri in rovesciata", label: "Tiri in rovesciata", type: "number" },
			{ name: "Tiri al volo", label: "Tiri al volo", type: "number" },
			{ name: "Tiri in acrobazia", label: "Tiri in acrobazia", type: "number" },
			{ name: "Tiri di piede con palla bassa", label: "Tiri di piede con palla bassa", type: "number" },
			{ name: "Tiri da fuori area", label: "Tiri da fuori area", type: "number" },
			{ name: "Tiri da dentro area di rigore", label: "Tiri da dentro area di rigore", type: "number" },
			{ name: "Tiri da dentro area di porta", label: "Tiri da dentro area di porta", type: "number" },
			{ name: "Tiri ribattuti o deviati", label: "Tiri ribattuti o deviati", type: "number" },
			{ name: "Tiri fuori dallo specchio", label: "Tiri fuori dallo specchio", type: "number" },
			{ name: "Tiri su azione", label: "Tiri su azione", type: "number" },
			{ name: "Tiri di testa su azione", label: "Tiri di testa su azione", type: "number" },
			{ name: "Tiri in rovesciata su azione", label: "Tiri in rovesciata su azione", type: "number" },
			{ name: "Tiri al volo su azione", label: "Tiri al volo su azione", type: "number" },
			{ name: "Tiri in acrobazia su azione", label: "Tiri in acrobazia su azione", type: "number" },
			{ name: "Tiri di piede su palla bassa da azione", label: "Tiri di piede su palla bassa da azione", type: "number" },
			{ name: "Tiri da piazzati in attacco", label: "Tiri da piazzati in attacco", type: "number" },
			{ name: "% efficacia piazzati in attacco", label: "% efficacia piazzati in attacco", type: "number" },
			{ name: "Tiri totali da calcio piazzato", label: "Tiri totali da calcio piazzato", type: "number" },
			{ name: "Tiri diretti da calcio piazzato", label: "Tiri diretti da calcio piazzato", type: "number" },
			{ name: "Tiri diretti da angolo", label: "Tiri diretti da angolo", type: "number" },
			{ name: "Tiri diretti da punizione in attacco", label: "Tiri diretti da punizione in attacco", type: "number" },
			{ name: "Tiri indiretti da calcio piazzato", label: "Tiri indiretti da calcio piazzato", type: "number" },
			{ name: "Tiri indiretti da angolo", label: "Tiri indiretti da angolo", type: "number" },
			{ name: "Tiri indiretti da punizione in attacco", label: "Tiri indiretti da punizione in attacco", type: "number" },
			{ name: "Tiri indiretti da laterale in attacco", label: "Tiri indiretti da laterale in attacco", type: "number" },
			{ name: "Tiri su rigore", label: "Tiri su rigore", type: "number" },
			{ name: "Tiri da punizione da destra", label: "Tiri da punizione da destra", type: "number" },
			{ name: "Tiri da punizione centrale", label: "Tiri da punizione centrale", type: "number" },
			{ name: "Tiri da punizione da sinistra", label: "Tiri da punizione da sinistra", type: "number" },
			{ name: "Tiri da angolo da destra", label: "Tiri da angolo da destra", type: "number" },
			{ name: "Tiri da angolo da sinistra", label: "Tiri da angolo da sinistra", type: "number" },
			{ name: "Tiri da laterale da destra", label: "Tiri da laterale da destra", type: "number" },
			{ name: "Tiri da laterale da sinistra", label: "Tiri da laterale da sinistra", type: "number" },
			{ name: "Tiri di testa da un calcio piazzato", label: "Tiri di testa da un calcio piazzato", type: "number" },
			{ name: "Tiri in rovesciata da un calcio piazzato", label: "Tiri in rovesciata da un calcio piazzato", type: "number" },
			{ name: "Tiri al volo da un calcio piazzato", label: "Tiri al volo da un calcio piazzato", type: "number" },
			{ name: "Tiri in acrobazia su calcio piazzato", label: "Tiri in acrobazia su calcio piazzato", type: "number" },
			{ name: "Tiri di piede su palla bassa da calcio piazzato", label: "Tiri di piede su palla bassa da calcio piazzato", type: "number" },
			{ name: "Palle giocate in zona area", label: "Palle giocate in zona area", type: "number" },
			{ name: "Rapidità nell'arrivare al tiro", label: "Rapidità nell'arrivare al tiro", type: "number" },
			{ name: "Rapidità nell'arrivare al tiro (passaggi)", label: "Rapidità nell'arrivare al tiro (passaggi)", type: "number" },
			{ name: "Reti da fuori area", label: "Reti da fuori area", type: "number" },
			{ name: "Reti da dentro area di porta", label: "Reti da dentro area di porta", type: "number" },
			{ name: "Reti di destro", label: "Reti di destro", type: "number" },
			{ name: "Reti di sinistro", label: "Reti di sinistro", type: "number" },
			{ name: "Reti di testa", label: "Reti di testa", type: "number" },
			{ name: "Reti in rovesciata", label: "Reti in rovesciata", type: "number" },
			{ name: "Reti al volo", label: "Reti al volo", type: "number" },
			{ name: "Reti totali su azione", label: "Reti totali su azione", type: "number" },
			{ name: "Reti totali su calcio piazzato", label: "Reti totali su calcio piazzato", type: "number" },
			{ name: "Reti dirette su calcio piazzato", label: "Reti dirette su calcio piazzato", type: "number" },
			{ name: "Reti dirette da angolo", label: "Reti dirette da angolo", type: "number" },
			{ name: "Reti dirette da punizione in attacco", label: "Reti dirette da punizione in attacco", type: "number" },
			{ name: "Reti indirette su calcio piazzato", label: "Reti indirette su calcio piazzato", type: "number" },
			{ name: "Reti indirette da angolo", label: "Reti indirette da angolo", type: "number" },
			{ name: "Reti indirette da punizione in attacco", label: "Reti indirette da punizione in attacco", type: "number" },
			{ name: "Reti indirette da laterale in attacco", label: "Reti indirette da laterale in attacco", type: "number" },
			{ name: "Rimesse dal fondo", label: "Rimesse dal fondo", type: "number" },
			{ name: "Piazzati in attacco", label: "Piazzati in attacco", type: "number" },
			{ name: "Falli laterali", label: "Falli laterali", type: "number" },
			{ name: "Falli laterali in attacco da destra con tiro", label: "Falli laterali in attacco da destra con tiro", type: "number" },
			{ name: "Falli laterali in attacco da destra senza tiro", label: "Falli laterali in attacco da destra senza tiro", type: "number" },
			{ name: "Falli laterali in attacco da sinistra con tiro", label: "Falli laterali in attacco da sinistra con tiro", type: "number" },
			{ name: "Falli laterali in attacco da sinistra senza tiro", label: "Falli laterali in attacco da sinistra senza tiro", type: "number" },
			{ name: "Angoli", label: "Angoli", type: "number" },
			{ name: "Angoli da destra", label: "Angoli da destra", type: "number" },
			{ name: "Angoli da destra con tiro", label: "Angoli da destra con tiro", type: "number" },
			{ name: "Angoli da destra senza tiro", label: "Angoli da destra senza tiro", type: "number" },
			{ name: "Angoli da sinistra", label: "Angoli da sinistra", type: "number" },
			{ name: "Angoli da sinistra con tiro", label: "Angoli da sinistra con tiro", type: "number" },
			{ name: "Angoli da sinistra senza tiro", label: "Angoli da sinistra senza tiro", type: "number" },
			{ name: "Punizioni", label: "Punizioni", type: "number" },
			{ name: "Punizioni in attacco", label: "Punizioni in attacco", type: "number" },
			{ name: "Punizioni in attacco da destra", label: "Punizioni in attacco da destra", type: "number" },
			{ name: "Punizioni in attacco da destra con tiro", label: "Punizioni in attacco da destra con tiro", type: "number" },
			{ name: "Punizioni in attacco da destra senza tiro", label: "Punizioni in attacco da destra senza tiro", type: "number" },
			{ name: "Punizioni in attacco centrali", label: "Punizioni in attacco centrali", type: "number" },
			{ name: "Punizioni in attacco centrali con tiro", label: "Punizioni in attacco centrali con tiro", type: "number" },
			{ name: "Punizioni in attacco centrali senza tiro", label: "Punizioni in attacco centrali senza tiro", type: "number" },
			{ name: "Punizioni in attacco da sinistra", label: "Punizioni in attacco da sinistra", type: "number" },
			{ name: "Punizioni in attacco da sinistra con tiro", label: "Punizioni in attacco da sinistra con tiro", type: "number" },
			{ name: "Punizioni in attacco da sinistra senza tiro", label: "Punizioni in attacco da sinistra senza tiro", type: "number" },
			{ name: "Punizioni alte laterali", label: "Punizioni alte laterali", type: "number" },
			{ name: "Punizioni alte laterali con tiro", label: "Punizioni alte laterali con tiro", type: "number" },
			{ name: "Punizioni alte laterali senza tiro", label: "Punizioni alte laterali senza tiro", type: "number" },
			{ name: "Punizioni alte laterali sinistre", label: "Punizioni alte laterali sinistre", type: "number" },
			{ name: "Punizioni alte laterali sinistre con tiro", label: "Punizioni alte laterali sinistre con tiro", type: "number" },
			{ name: "Punizioni alte laterali sinistre senza tiro", label: "Punizioni alte laterali sinistre senza tiro", type: "number" },
			{ name: "Punizioni alte laterali destre", label: "Punizioni alte laterali destre", type: "number" },
			{ name: "Punizioni alte laterali destre con tiro", label: "Punizioni alte laterali destre con tiro", type: "number" },
			{ name: "Punizioni alte laterali destre senza tiro", label: "Punizioni alte laterali destre senza tiro", type: "number" },
			{ name: "Punizioni centrali", label: "Punizioni centrali", type: "number" },
			{ name: "Punizioni centrali con tiro", label: "Punizioni centrali con tiro", type: "number" },
			{ name: "Punizioni centrali senza tiro", label: "Punizioni centrali senza tiro", type: "number" },
			{ name: "Punizioni centrali dal limite", label: "Punizioni centrali dal limite", type: "number" },
			{ name: "Punizioni centrali dal limite con tiro", label: "Punizioni centrali dal limite con tiro", type: "number" },
			{ name: "Punizioni centrali dal limite senza tiro", label: "Punizioni centrali dal limite senza tiro", type: "number" },
			{ name: "Punizioni basse laterali", label: "Punizioni basse laterali", type: "number" },
			{ name: "Punizioni basse laterali con tiro", label: "Punizioni basse laterali con tiro", type: "number" },
			{ name: "Punizioni basse laterali senza tiro", label: "Punizioni basse laterali senza tiro", type: "number" },
			{ name: "Punizioni basse laterali sinistre", label: "Punizioni basse laterali sinistre", type: "number" },
			{ name: "Punizioni basse laterali sinistre con tiro", label: "Punizioni basse laterali sinistre con tiro", type: "number" },
			{ name: "Punizioni basse laterali sinistre senza tiro", label: "Punizioni basse laterali sinistre senza tiro", type: "number" },
			{ name: "Punizioni basse laterali destre", label: "Punizioni basse laterali destre", type: "number" },
			{ name: "Punizioni basse laterali destre con tiro", label: "Punizioni basse laterali destre con tiro", type: "number" },
			{ name: "Punizioni basse laterali destre senza tiro", label: "Punizioni basse laterali destre senza tiro", type: "number" },
			{ name: "Rigori", label: "Rigori", type: "number" },
			{ name: "Rigori sbagliati", label: "Rigori sbagliati", type: "number" },
			{ name: "Rigori trasformati", label: "Rigori trasformati", type: "number" },
			{ name: "Falli laterali in attacco (avversari)", label: "Falli laterali in attacco (avversari)", type: "number" },
			{ name: "Falli laterali in attacco da destra con tiro (avversari)", label: "Falli laterali in attacco da destra con tiro (avversari)", type: "number" },
			{ name: "Falli laterali in attacco da destra senza tiro (avversari)", label: "Falli laterali in attacco da destra senza tiro (avversari)", type: "number" },
			{ name: "Falli laterali in attacco da sinistra con tiro (avversari)", label: "Falli laterali in attacco da sinistra con tiro (avversari)", type: "number" },
			{ name: "Falli laterali in attacco da sinistra senza tiro (avversari)", label: "Falli laterali in attacco da sinistra senza tiro (avversari)", type: "number" },
			{ name: "Punizioni in attacco (avversari)", label: "Punizioni in attacco (avversari)", type: "number" },
			{ name: "Punizioni in attacco da destra (avversari)", label: "Punizioni in attacco da destra (avversari)", type: "number" },
			{ name: "Punizioni in attacco da destra con tiro (avversari)", label: "Punizioni in attacco da destra con tiro (avversari)", type: "number" },
			{ name: "Punizioni in attacco da destra senza tiro (avversari)", label: "Punizioni in attacco da destra senza tiro (avversari)", type: "number" },
			{ name: "Punizioni in attacco centrali (avversari)", label: "Punizioni in attacco centrali (avversari)", type: "number" },
			{ name: "Punizioni in attacco centrali con tiro (avversari)", label: "Punizioni in attacco centrali con tiro (avversari)", type: "number" },
			{ name: "Punizioni in attacco centrali senza tiro (avversari)", label: "Punizioni in attacco centrali senza tiro (avversari)", type: "number" },
			{ name: "Punizioni in attacco da sinistra (avversari)", label: "Punizioni in attacco da sinistra (avversari)", type: "number" },
			{ name: "Punizioni in attacco da sinistra con tiro (avversari)", label: "Punizioni in attacco da sinistra con tiro (avversari)", type: "number" },
			{ name: "Punizioni in attacco da sinistra senza tiro (avversari)", label: "Punizioni in attacco da sinistra senza tiro (avversari)", type: "number" },
			{ name: "Punizioni alte laterali (avversari)", label: "Punizioni alte laterali (avversari)", type: "number" },
			{ name: "Punizioni alte laterali con tiro (avversari)", label: "Punizioni alte laterali con tiro (avversari)", type: "number" },
			{ name: "Punizioni alte laterali senza tiro (avversari)", label: "Punizioni alte laterali senza tiro (avversari)", type: "number" },
			{ name: "Punizioni alte laterali sinistre (avversari)", label: "Punizioni alte laterali sinistre (avversari)", type: "number" },
			{ name: "Punizioni alte laterali sinistre con tiro (avversari)", label: "Punizioni alte laterali sinistre con tiro (avversari)", type: "number" },
			{ name: "Punizioni alte laterali sinistre senza tiro (avversari)", label: "Punizioni alte laterali sinistre senza tiro (avversari)", type: "number" },
			{ name: "Punizioni alte laterali destre (avversari)", label: "Punizioni alte laterali destre (avversari)", type: "number" },
			{ name: "Punizioni alte laterali destre con tiro (avversari)", label: "Punizioni alte laterali destre con tiro (avversari)", type: "number" },
			{ name: "Punizioni alte laterali destre senza tiro (avversari)", label: "Punizioni alte laterali destre senza tiro (avversari)", type: "number" },
			{ name: "Punizioni centrali (avversari)", label: "Punizioni centrali (avversari)", type: "number" },
			{ name: "Punizioni centrali con tiro (avversari)", label: "Punizioni centrali con tiro (avversari)", type: "number" },
			{ name: "Punizioni centrali senza tiro (avversari)", label: "Punizioni centrali senza tiro (avversari)", type: "number" },
			{ name: "Punizioni centrali dal limite (avversari)", label: "Punizioni centrali dal limite (avversari)", type: "number" },
			{ name: "Punizioni centrali dal limite con tiro (avversari)", label: "Punizioni centrali dal limite con tiro (avversari)", type: "number" },
			{ name: "Punizioni centrali dal limite senza tiro (avversari)", label: "Punizioni centrali dal limite senza tiro (avversari)", type: "number" },
			{ name: "Punizioni basse laterali (avversari)", label: "Punizioni basse laterali (avversari)", type: "number" },
			{ name: "Punizioni basse laterali con tiro (avversari)", label: "Punizioni basse laterali con tiro (avversari)", type: "number" },
			{ name: "Punizioni basse laterali senza tiro (avversari)", label: "Punizioni basse laterali senza tiro (avversari)", type: "number" },
			{ name: "Punizioni basse laterali sinistre (avversari)", label: "Punizioni basse laterali sinistre (avversari)", type: "number" },
			{ name: "Punizioni basse laterali sinistre con tiro (avversari)", label: "Punizioni basse laterali sinistre con tiro (avversari)", type: "number" },
			{ name: "Punizioni basse laterali sinistre senza tiro (avversari)", label: "Punizioni basse laterali sinistre senza tiro (avversari)", type: "number" },
			{ name: "Punizioni basse laterali destre (avversari)", label: "Punizioni basse laterali destre (avversari)", type: "number" },
			{ name: "Punizioni basse laterali destre con tiro (avversari)", label: "Punizioni basse laterali destre con tiro (avversari)", type: "number" },
			{ name: "Punizioni basse laterali destre senza tiro (avversari)", label: "Punizioni basse laterali destre senza tiro (avversari)", type: "number" },
			{ name: "Angoli (avversari)", label: "Angoli (avversari)", type: "number" },
			{ name: "Angoli da sinistra (avversari)", label: "Angoli da sinistra (avversari)", type: "number" },
			{ name: "Angoli da sinistra con tiro (avversari)", label: "Angoli da sinistra con tiro (avversari)", type: "number" },
			{ name: "Angoli da sinistra senza tiro (avversari)", label: "Angoli da sinistra senza tiro (avversari)", type: "number" },
			{ name: "Angoli da destra (avversari)", label: "Angoli da destra (avversari)", type: "number" },
			{ name: "Angoli da destra con tiro (avversari)", label: "Angoli da destra con tiro (avversari)", type: "number" },
			{ name: "Angoli da destra senza tiro (avversari)", label: "Angoli da destra senza tiro (avversari)", type: "number" },
			{ name: "Rigori (avversari)", label: "Rigori (avversari)", type: "number" },
			{ name: "Rigori sbagliati (avversari)", label: "Rigori sbagliati (avversari)", type: "number" },
			{ name: "Palle giocate (avversari)", label: "Palle giocate (avversari)", type: "number" },
			{ name: "Passaggi riusciti (avversari)", label: "Passaggi riusciti (avversari)", type: "number" },
			{ name: "Possesso palla (avversari)", label: "Possesso palla (avversari)", type: "number" },
			{ name: "Velocità di gioco (avversari)", label: "Velocità di gioco (avversari)", type: "number" },
			{ name: "Passaggi rapidi (avversari)", label: "Passaggi rapidi (avversari)", type: "number" },
			{ name: "Giocate utili (avversari)", label: "Giocate utili (avversari)", type: "number" },
			{ name: "% sulle palle giocate (avversari)", label: "% sulle palle giocate (avversari)", type: "number" },
			{ name: "Palle giocate sulla fascia destra (avversari)", label: "Palle giocate sulla fascia destra (avversari)", type: "number" },
			{ name: "% palle giocate sulla fascia destra (avversari)", label: "% palle giocate sulla fascia destra (avversari)", type: "number" },
			{ name: "Palle giocate sulla fascia centrale (avversari)", label: "Palle giocate sulla fascia centrale (avversari)", type: "number" },
			{ name: "% palle giocate sulla fascia centrale (avversari)", label: "% palle giocate sulla fascia centrale (avversari)", type: "number" },
			{ name: "Palle giocate sulla fascia sinistra (avversari)", label: "Palle giocate sulla fascia sinistra (avversari)", type: "number" },
			{ name: "% palle giocate sulla fascia sinistra (avversari)", label: "% palle giocate sulla fascia sinistra (avversari)", type: "number" },
			{ name: "Palle giocate in difesa (avversari)", label: "Palle giocate in difesa (avversari)", type: "number" },
			{ name: "% palle giocate in difesa (avversari)", label: "% palle giocate in difesa (avversari)", type: "number" },
			{ name: "Palle giocate a centrocampo (avversari)", label: "Palle giocate a centrocampo (avversari)", type: "number" },
			{ name: "% palle giocate a centrocampo (avversari)", label: "% palle giocate a centrocampo (avversari)", type: "number" },
			{ name: "Palle giocate in attacco (avversari)", label: "Palle giocate in attacco (avversari)", type: "number" },
			{ name: "% palle giocate in attacco (avversari)", label: "% palle giocate in attacco (avversari)", type: "number" },
			{ name: "Palle giocate totali (avversari)", label: "Palle giocate totali (avversari)", type: "number" },
			{ name: "Misura squadra (avversari)", label: "Misura squadra (avversari)", type: "number" },
			{ name: "Baricentro (mt) (avversari)", label: "Baricentro (mt) (avversari)", type: "number" },
			{ name: "Parate (avversari)", label: "Parate (avversari)", type: "number" },
			{ name: "Parate su rigore (avversari)", label: "Parate su rigore (avversari)", type: "number" },
			{ name: "Rapporto fra reti subite e tiri dentro (avversari)", label: "Rapporto fra reti subite e tiri dentro (avversari)", type: "number" },
			{ name: "Uscite alte (avversari)", label: "Uscite alte (avversari)", type: "number" },
			{ name: "Uscite basse (avversari)", label: "Uscite basse (avversari)", type: "number" },
			{ name: "Recuperi in attacco (avversari)", label: "Recuperi in attacco (avversari)", type: "number" },
			{ name: "Cambio di gioco (avversari)", label: "Cambio di gioco (avversari)", type: "number" },
			{ name: "Ripartenze (avversari)", label: "Ripartenze (avversari)", type: "number" },
			{ name: "Palle a scavalcare il centrocampo (avversari)", label: "Palle a scavalcare il centrocampo (avversari)", type: "number" },
			{ name: "% palle a scavalcare il centrocampo (avversari)", label: "% palle a scavalcare il centrocampo (avversari)", type: "number" },
			{ name: "Azioni manovrate da dietro (avversari)", label: "Azioni manovrate da dietro (avversari)", type: "number" },
			{ name: "% azioni manovrate da dietro (avversari)", label: "% azioni manovrate da dietro (avversari)", type: "number" },
			{ name: "Passaggi lunghi (avversari)", label: "Passaggi lunghi (avversari)", type: "number" },
			{ name: "Passaggi lunghi utili (avversari)", label: "Passaggi lunghi utili (avversari)", type: "number" },
			{ name: "Rapporto fra passaggi lunghi utili e totale fatti (avversari)", label: "Rapporto fra passaggi lunghi utili e totale fatti (avversari)", type: "number" },
			{ name: "Pallonetti (avversari)", label: "Pallonetti (avversari)", type: "number" },
			{ name: "Pallonetti utili (avversari)", label: "Pallonetti utili (avversari)", type: "number" },
			{ name: "Rapporto fra pallonetti utili e totale fatti (avversari)", label: "Rapporto fra pallonetti utili e totale fatti (avversari)", type: "number" },
			{ name: "Passaggi filtranti (avversari)", label: "Passaggi filtranti (avversari)", type: "number" },
			{ name: "Passaggi filtranti utili (avversari)", label: "Passaggi filtranti utili (avversari)", type: "number" },
			{ name: "Rapporto fra passaggi filtranti utili e totale fatti (avversari)", label: "Rapporto fra passaggi filtranti utili e totale fatti (avversari)", type: "number" },
			{ name: "Cross (avversari)", label: "Cross (avversari)", type: "number" },
			{ name: "Cross su azione (avversari)", label: "Cross su azione (avversari)", type: "number" },
			{ name: "Cross su azione dal fondo (avversari)", label: "Cross su azione dal fondo (avversari)", type: "number" },
			{ name: "Cross su calcio piazzato (avversari)", label: "Cross su calcio piazzato (avversari)", type: "number" },
			{ name: "Cross utili (avversari)", label: "Cross utili (avversari)", type: "number" },
			{ name: "Rapporto fra cross utili e totale fatti (avversari)", label: "Rapporto fra cross utili e totale fatti (avversari)", type: "number" },
			{ name: "Passaggi lungo linea (avversari)", label: "Passaggi lungo linea (avversari)", type: "number" },
			{ name: "Passaggi lungo linea utili (avversari)", label: "Passaggi lungo linea utili (avversari)", type: "number" },
			{ name: "Dai e vai (avversari)", label: "Dai e vai (avversari)", type: "number" },
			{ name: "Sponde (avversari)", label: "Sponde (avversari)", type: "number" },
			{ name: "Tagli dentro (avversari)", label: "Tagli dentro (avversari)", type: "number" },
			{ name: "Tagli fuori (avversari)", label: "Tagli fuori (avversari)", type: "number" },
			{ name: "Allargamento (avversari)", label: "Allargamento (avversari)", type: "number" },
			{ name: "Dribbling (avversari)", label: "Dribbling (avversari)", type: "number" },
			{ name: "Dribbling utili (avversari)", label: "Dribbling utili (avversari)", type: "number" },
			{ name: "Assist (avversari)", label: "Assist (avversari)", type: "number" },
			{ name: "Assist vincenti (avversari)", label: "Assist vincenti (avversari)", type: "number" },
			{ name: "Occasioni (avversari)", label: "Occasioni (avversari)", type: "number" },
			{ name: "% occasioni sfruttate (avversari)", label: "% occasioni sfruttate (avversari)", type: "number" },
			{ name: "Occasioni su azione (avversari)", label: "Occasioni su azione (avversari)", type: "number" },
			{ name: "Occasioni su calcio piazzato (avversari)", label: "Occasioni su calcio piazzato (avversari)", type: "number" },
			{ name: "Occasioni dirette su calcio piazzato (avversari)", label: "Occasioni dirette su calcio piazzato (avversari)", type: "number" },
			{ name: "Occasioni dirette da angolo (avversari)", label: "Occasioni dirette da angolo (avversari)", type: "number" },
			{ name: "Occasioni dirette da punizione in attacco (avversari)", label: "Occasioni dirette da punizione in attacco (avversari)", type: "number" },
			{ name: "Occasioni indirette su calcio piazzato (avversari)", label: "Occasioni indirette su calcio piazzato (avversari)", type: "number" },
			{ name: "Occasioni indirette da angolo (avversari)", label: "Occasioni indirette da angolo (avversari)", type: "number" },
			{ name: "Occasioni indirette da punizione in attacco (avversari)", label: "Occasioni indirette da punizione in attacco (avversari)", type: "number" },
			{ name: "Occasioni indirette da laterale in attacco (avversari)", label: "Occasioni indirette da laterale in attacco (avversari)", type: "number" },
			{ name: "Tiri (avversari)", label: "Tiri (avversari)", type: "number" },
			{ name: "Capacità realizzativa (avversari)", label: "Capacità realizzativa (avversari)", type: "number" },
			{ name: "Tiri da fuori area (avversari)", label: "Tiri da fuori area (avversari)", type: "number" },
			{ name: "Tiri dentro (avversari)", label: "Tiri dentro (avversari)", type: "number" },
			{ name: "Tiri fuori (avversari)", label: "Tiri fuori (avversari)", type: "number" },
			{ name: "Tiri di destro (avversari)", label: "Tiri di destro (avversari)", type: "number" },
			{ name: "Tiri di sinistro (avversari)", label: "Tiri di sinistro (avversari)", type: "number" },
			{ name: "Tiri di testa (avversari)", label: "Tiri di testa (avversari)", type: "number" },
			{ name: "Tiri da sviluppo azione di gioco (avversari)", label: "Tiri da sviluppo azione di gioco (avversari)", type: "number" },
			{ name: "Tiri indiretti da calcio piazzato (avversari)", label: "Tiri indiretti da calcio piazzato (avversari)", type: "number" },
			{ name: "Tiri diretti da calcio piazzato (avversari)", label: "Tiri diretti da calcio piazzato (avversari)", type: "number" },
			{ name: "Tiri su punizione da destra (avversari)", label: "Tiri su punizione da destra (avversari)", type: "number" },
			{ name: "Tiri da punizione centrale (avversari)", label: "Tiri da punizione centrale (avversari)", type: "number" },
			{ name: "Tiri da punizione da sinistra (avversari)", label: "Tiri da punizione da sinistra (avversari)", type: "number" },
			{ name: "Tiri da angolo da destra (avversari)", label: "Tiri da angolo da destra (avversari)", type: "number" },
			{ name: "Tiri da angolo da sinistra (avversari)", label: "Tiri da angolo da sinistra (avversari)", type: "number" },
			{ name: "Tiri da laterale da destra (avversari)", label: "Tiri da laterale da destra (avversari)", type: "number" },
			{ name: "Tiri da laterale da sinistra (avversari)", label: "Tiri da laterale da sinistra (avversari)", type: "number" },
			{ name: "Tiri da dentro area di rigore (avversari)", label: "Tiri da dentro area di rigore (avversari)", type: "number" },
			{ name: "Tiri da dentro area di porta (avversari)", label: "Tiri da dentro area di porta (avversari)", type: "number" },
			{ name: "Tiri ribattuti o deviati (avversari)", label: "Tiri ribattuti o deviati (avversari)", type: "number" },
			{ name: "Tiri fuori dallo specchio (avversari)", label: "Tiri fuori dallo specchio (avversari)", type: "number" },
			{ name: "Reti da fuori area (avversari)", label: "Reti da fuori area (avversari)", type: "number" },
			{ name: "Reti da dentro area di porta (avversari)", label: "Reti da dentro area di porta (avversari)", type: "number" },
			{ name: "Reti di destro (avversari)", label: "Reti di destro (avversari)", type: "number" },
			{ name: "Reti di sinistro (avversari)", label: "Reti di sinistro (avversari)", type: "number" },
			{ name: "Reti di testa (avversari)", label: "Reti di testa (avversari)", type: "number" },
			{ name: "Reti in rovesciata (avversari)", label: "Reti in rovesciata (avversari)", type: "number" },
			{ name: "Reti al volo (avversari)", label: "Reti al volo (avversari)", type: "number" },
			{ name: "Palle giocate in zona area dagli avversari (avversari)", label: "Palle giocate in zona area dagli avversari (avversari)", type: "number" },
			{ name: "Rapidità nell'arrivare al tiro (avversari)", label: "Rapidità nell'arrivare al tiro (avversari)", type: "number" },
			{ name: "Rapidità nell'arrivare al tiro (passaggi) (avversari)", label: "Rapidità nell'arrivare al tiro (passaggi) (avversari)", type: "number" },
			{ name: "Tiri diretti da angolo (avversari)", label: "Tiri diretti da angolo (avversari)", type: "number" },
			{ name: "Tiri diretti da punizione in attacco (avversari)", label: "Tiri diretti da punizione in attacco (avversari)", type: "number" },
			{ name: "Tiri indiretti da angolo (avversari)", label: "Tiri indiretti da angolo (avversari)", type: "number" },
			{ name: "Tiri indiretti da punizione in attacco (avversari)", label: "Tiri indiretti da punizione in attacco (avversari)", type: "number" },
			{ name: "Tiri indiretti da laterale in attacco (avversari)", label: "Tiri indiretti da laterale in attacco (avversari)", type: "number" },
			{ name: "Reti dirette da angolo (avversari)", label: "Reti dirette da angolo (avversari)", type: "number" },
			{ name: "Reti dirette da punizione in attacco (avversari)", label: "Reti dirette da punizione in attacco (avversari)", type: "number" },
			{ name: "Reti indirette da angolo (avversari)", label: "Reti indirette da angolo (avversari)", type: "number" },
			{ name: "Reti indirette da punizione in attacco (avversari)", label: "Reti indirette da punizione in attacco (avversari)", type: "number" },
			{ name: "Reti indirette da laterale in attacco (avversari)", label: "Reti indirette da laterale in attacco (avversari)", type: "number" }
		],
		goalsScoredField: "Reti",
		goalsConcedField: "Reti subite"
	}
};
