export default {
	Playertek: {
		rawMetrics: [
			{ name: "Date", label: "Date", type: "number" },
			{ name: "Session Title", label: "Session Title", type: "number" },
			{ name: "Player Name", label: "Player Name", type: "number" },
			{ name: "Split Name", label: "Split Name", type: "number" },
			{ name: "Tags", label: "Tags", type: "number" },
			{ name: "Split Start Time", label: "Split Start Time", type: "number" },
			{ name: "Split End Time", label: "Split End Time", type: "number" },
			{ name: "Duration", label: "Duration", type: "number" },
			{ name: "Distance (km)", label: "Distance (km)", type: "number" },
			{ name: "Power Plays", label: "Power Plays", type: "number" },
			{ name: "Sprint Distance (m)", label: "Sprint Distance (m)", type: "number" },
			{ name: "Energy (kcal)", label: "Energy (kcal)", type: "number" },
			{ name: "Impacts", label: "Impacts", type: "number" },
			{ name: "Top Speed (m/s)", label: "Top Speed (m/s)", type: "number" },
			{ name: "Distance Per Min (m/min)", label: "Distance Per Min (m/min)", type: "number" },
			{ name: "Power Score (w/kg)", label: "Power Score (w/kg)", type: "number" },
			{ name: "Player Load", label: "Player Load", type: "number" },
			{ name: "Work Ratio", label: "Work Ratio", type: "number" },
			{ name: "Distance in Speed Zone 1  (km)", label: "Distance in Speed Zone 1  (km)", type: "number" },
			{ name: "Distance in Speed Zone 2  (km)", label: "Distance in Speed Zone 2  (km)", type: "number" },
			{ name: "Distance in Speed Zone 3  (km)", label: "Distance in Speed Zone 3  (km)", type: "number" },
			{ name: "Distance in Speed Zone 4  (km)", label: "Distance in Speed Zone 4  (km)", type: "number" },
			{ name: "Distance in Speed Zone 5  (km)", label: "Distance in Speed Zone 5  (km)", type: "number" },
			{ name: "Time in Speed Zone 1 (secs)", label: "Time in Speed Zone 1 (secs)", type: "number" },
			{ name: "Time in Speed Zone 2 (secs)", label: "Time in Speed Zone 2 (secs)", type: "number" },
			{ name: "Time in Speed Zone 3 (secs)", label: "Time in Speed Zone 3 (secs)", type: "number" },
			{ name: "Time in Speed Zone 4 (secs)", label: "Time in Speed Zone 4 (secs)", type: "number" },
			{ name: "Time in Speed Zone 5 (secs)", label: "Time in Speed Zone 5 (secs)", type: "number" },
			{ name: "Impact Zones: 3 - 5 G (Impacts)", label: "Impact Zones: 3 - 5 G (Impacts)", type: "number" },
			{ name: "Impact Zones: 5 - 10 G (Impacts)", label: "Impact Zones: 5 - 10 G (Impacts)", type: "number" },
			{ name: "Impact Zones: 10 - 15 G (Impacts)", label: "Impact Zones: 10 - 15 G (Impacts)", type: "number" },
			{ name: "Impact Zones: 15 - 20 G (Impacts)", label: "Impact Zones: 15 - 20 G (Impacts)", type: "number" },
			{ name: "Impact Zones: > 20 G (Impacts)", label: "Impact Zones: > 20 G (Impacts)", type: "number" },
			{ name: "Power Play Duration Zones: 0 - 2.5 s (Power Plays)", label: "Power Play Duration Zones: 0 - 2.5 s (Power Plays)", type: "number" },
			{ name: "Power Play Duration Zones: 2.5 - 5 s (Power Plays)", label: "Power Play Duration Zones: 2.5 - 5 s (Power Plays)", type: "number" },
			{ name: "Power Play Duration Zones: 5 - 7.5 s (Power Plays)", label: "Power Play Duration Zones: 5 - 7.5 s (Power Plays)", type: "number" },
			{ name: "Power Play Duration Zones: 7.5 - 10 s (Power Plays)", label: "Power Play Duration Zones: 7.5 - 10 s (Power Plays)", type: "number" },
			{ name: "Power Play Duration Zones: > 10 s (Power Plays)", label: "Power Play Duration Zones: > 10 s (Power Plays)", type: "number" },
			{ name: "Distance in Deceleration Zones: 0 - 1 m/s/s  (km)", label: "Distance in Deceleration Zones: 0 - 1 m/s/s  (km)", type: "number" },
			{ name: "Distance in Deceleration Zones: 1 - 2 m/s/s  (km)", label: "Distance in Deceleration Zones: 1 - 2 m/s/s  (km)", type: "number" },
			{ name: "Distance in Deceleration Zones: 2 - 3 m/s/s  (km)", label: "Distance in Deceleration Zones: 2 - 3 m/s/s  (km)", type: "number" },
			{ name: "Distance in Deceleration Zones: 3 - 4 m/s/s  (km)", label: "Distance in Deceleration Zones: 3 - 4 m/s/s  (km)", type: "number" },
			{ name: "Distance in Deceleration Zones: > 4 m/s/s  (km)", label: "Distance in Deceleration Zones: > 4 m/s/s  (km)", type: "number" },
			{ name: "Time in Deceleration Zones: 0 - 1 m/s/s (secs)", label: "Time in Deceleration Zones: 0 - 1 m/s/s (secs)", type: "number" },
			{ name: "Time in Deceleration Zones: 1 - 2 m/s/s (secs)", label: "Time in Deceleration Zones: 1 - 2 m/s/s (secs)", type: "number" },
			{ name: "Time in Deceleration Zones: 2 - 3 m/s/s (secs)", label: "Time in Deceleration Zones: 2 - 3 m/s/s (secs)", type: "number" },
			{ name: "Time in Deceleration Zones: 3 - 4 m/s/s (secs)", label: "Time in Deceleration Zones: 3 - 4 m/s/s (secs)", type: "number" },
			{ name: "Time in Deceleration Zones: > 4 m/s/s (secs)", label: "Time in Deceleration Zones: > 4 m/s/s (secs)", type: "number" },
			{ name: "Distance in Acceleration Zones: 0 - 1 m/s/s  (km)", label: "Distance in Acceleration Zones: 0 - 1 m/s/s  (km)", type: "number" },
			{ name: "Distance in Acceleration Zones: 1 - 2 m/s/s  (km)", label: "Distance in Acceleration Zones: 1 - 2 m/s/s  (km)", type: "number" },
			{ name: "Distance in Acceleration Zones: 2 - 3 m/s/s  (km)", label: "Distance in Acceleration Zones: 2 - 3 m/s/s  (km)", type: "number" },
			{ name: "Distance in Acceleration Zones: 3 - 4 m/s/s  (km)", label: "Distance in Acceleration Zones: 3 - 4 m/s/s  (km)", type: "number" },
			{ name: "Distance in Acceleration Zones: > 4 m/s/s  (km)", label: "Distance in Acceleration Zones: > 4 m/s/s  (km)", type: "number" },
			{ name: "Time in Acceleration Zones: 0 - 1 m/s/s (secs)", label: "Time in Acceleration Zones: 0 - 1 m/s/s (secs)", type: "number" },
			{ name: "Time in Acceleration Zones: 1 - 2 m/s/s (secs)", label: "Time in Acceleration Zones: 1 - 2 m/s/s (secs)", type: "number" },
			{ name: "Time in Acceleration Zones: 2 - 3 m/s/s (secs)", label: "Time in Acceleration Zones: 2 - 3 m/s/s (secs)", type: "number" },
			{ name: "Time in Acceleration Zones: 3 - 4 m/s/s (secs)", label: "Time in Acceleration Zones: 3 - 4 m/s/s (secs)", type: "number" },
			{ name: "Time in Acceleration Zones: > 4 m/s/s (secs)", label: "Time in Acceleration Zones: > 4 m/s/s (secs)", type: "number" },
			{ name: "Distance in Power Zone: 0 - 5 w/kg  (km)", label: "Distance in Power Zone: 0 - 5 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 5 - 10 w/kg  (km)", label: "Distance in Power Zone: 5 - 10 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 10 - 15 w/kg  (km)", label: "Distance in Power Zone: 10 - 15 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 15 - 20 w/kg  (km)", label: "Distance in Power Zone: 15 - 20 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 20 - 25 w/kg  (km)", label: "Distance in Power Zone: 20 - 25 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 25 - 30 w/kg  (km)", label: "Distance in Power Zone: 25 - 30 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 30 - 35 w/kg  (km)", label: "Distance in Power Zone: 30 - 35 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 35 - 40 w/kg  (km)", label: "Distance in Power Zone: 35 - 40 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 40 - 45 w/kg  (km)", label: "Distance in Power Zone: 40 - 45 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: 45 - 50 w/kg  (km)", label: "Distance in Power Zone: 45 - 50 w/kg  (km)", type: "number" },
			{ name: "Distance in Power Zone: > 50 w/kg  (km)", label: "Distance in Power Zone: > 50 w/kg  (km)", type: "number" },
			{ name: "Time in Power Zone: 0 - 5 w/kg (secs)", label: "Time in Power Zone: 0 - 5 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 5 - 10 w/kg (secs)", label: "Time in Power Zone: 5 - 10 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 10 - 15 w/kg (secs)", label: "Time in Power Zone: 10 - 15 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 15 - 20 w/kg (secs)", label: "Time in Power Zone: 15 - 20 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 20 - 25 w/kg (secs)", label: "Time in Power Zone: 20 - 25 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 25 - 30 w/kg (secs)", label: "Time in Power Zone: 25 - 30 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 30 - 35 w/kg (secs)", label: "Time in Power Zone: 30 - 35 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 35 - 40 w/kg (secs)", label: "Time in Power Zone: 35 - 40 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 40 - 45 w/kg (secs)", label: "Time in Power Zone: 40 - 45 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: 45 - 50 w/kg (secs)", label: "Time in Power Zone: 45 - 50 w/kg (secs)", type: "number" },
			{ name: "Time in Power Zone: > 50 w/kg (secs)", label: "Time in Power Zone: > 50 w/kg (secs)", type: "number" },
			{ name: "Time in HR Load Zone 0% - 60% Max HR(secs)", label: "Time in HR Load Zone 0% - 60% Max HR(secs)", type: "number" },
			{ name: "Time in HR Load Zone 60% - 75% Max HR (secs)", label: "Time in HR Load Zone 60% - 75% Max HR (secs)", type: "number" },
			{ name: "Time in HR Load Zone 75% - 85% Max HR (secs)", label: "Time in HR Load Zone 75% - 85% Max HR (secs)", type: "number" },
			{ name: "Time in HR Load Zone 85% - 96% Max HR (secs)", label: "Time in HR Load Zone 85% - 96% Max HR (secs)", type: "number" },
			{ name: "Time in HR Load Zone 96% - 100% Max HR (secs)", label: "Time in HR Load Zone 96% - 100% Max HR (secs)", type: "number" },
			{ name: "Accelerations Zone Count: 0 - 1 m/s/s", label: "Accelerations Zone Count: 0 - 1 m/s/s", type: "number" },
			{ name: "Accelerations Zone Count: 1 - 2 m/s/s", label: "Accelerations Zone Count: 1 - 2 m/s/s", type: "number" },
			{ name: "Accelerations Zone Count: 2 - 3 m/s/s", label: "Accelerations Zone Count: 2 - 3 m/s/s", type: "number" },
			{ name: "Accelerations Zone Count: 3 - 4 m/s/s", label: "Accelerations Zone Count: 3 - 4 m/s/s", type: "number" },
			{ name: "Accelerations Zone Count: > 4 m/s/s", label: "Accelerations Zone Count: > 4 m/s/s", type: "number" },
			{ name: "Deceleration Zone Count: 0 - 1 m/s/s", label: "Deceleration Zone Count: 0 - 1 m/s/s", type: "number" },
			{ name: "Deceleration Zone Count: 1 - 2 m/s/s", label: "Deceleration Zone Count: 1 - 2 m/s/s", type: "number" },
			{ name: "Deceleration Zone Count: 2 - 3 m/s/s", label: "Deceleration Zone Count: 2 - 3 m/s/s", type: "number" },
			{ name: "Deceleration Zone Count: 3 - 4 m/s/s", label: "Deceleration Zone Count: 3 - 4 m/s/s", type: "number" },
			{ name: "Deceleration Zone Count: > 4 m/s/s", label: "Deceleration Zone Count: > 4 m/s/s", type: "number" }
		],
		splitNameColumn: "Split Name",
		dateColumn: "Date",
		dateColumnFormat: 0,
		startTimeColumn: "Split Start Time",
		startTimeColumnFormat: 4,
		endTimeColumn: "Split End Time",
		endTimeColumnFormat: 4,
		playerNameColumn: "Player Name",
		durationColumn: null,
		durationColumnFormat: null,
		_gpsMetricsMapping: [
			{
				columnName: "rpe",
				expression: null,
				columnLabel: "RPE"
			},
			{
				columnName: "rpeTl",
				expression: null,
				columnLabel: "RPE TL"
			},
			{
				columnName: "heartRate85to90",
				expression: "{Time in HR Load Zone 85% - 96% Max HR (secs)}/60",
				columnLabel: "HR 85-90 (min)"
			},
			{
				columnName: "heartRateGr90",
				expression: "{Time in HR Load Zone 96% - 100% Max HR (secs)}/60",
				columnLabel: "HR >90 (min)"
			},
			{
				columnName: "totalDistance",
				expression: "{Distance (km)}",
				columnLabel: "Total Distance (Km)"
			},
			{
				columnName: "sprintDistance",
				expression: "{Distance in Speed Zone 5 (km)}*1000",
				columnLabel: "Sprint Distance (m)"
			},
			{
				columnName: "highspeedRunningDistance",
				expression: "{Sprint Distance (m)}",
				columnLabel: "High Speed Running Distance (m)"
			},
			{
				columnName: "powerDistance",
				expression:
					"({Distance in Power Zone: 20 - 25 w/kg (km)}+{Distance in Power Zone: 25 - 30 w/kg (km)}+{Distance in Power Zone: 30 - 35 w/kg (km)}+{Distance in Power Zone: 35 - 40 w/kg (km)}+{Distance in Power Zone: 40 - 45 w/kg (km)}+{Distance in Power Zone: 45 - 50 w/kg (km)}+{Distance in Power Zone: > 50 w/kg (km)})*1000",
				columnLabel: "Power Distance (m)"
			},
			{
				columnName: "highPowerDistance",
				expression:
					"({Distance in Power Zone: 25 - 30 w/kg (km)}+{Distance in Power Zone: 30 - 35 w/kg (km)}+{Distance in Power Zone: 35 - 40 w/kg (km)}+{Distance in Power Zone: 40 - 45 w/kg (km)}+{Distance in Power Zone: 45 - 50 w/kg (km)}+{Distance in Power Zone: > 50 w/kg (km)})*1000",
				columnLabel: "High Power Distance (m)"
			},
			{
				columnName: "powerPlays",
				expression: "{Power Plays}",
				columnLabel: "Power Plays (No)"
			},
			{
				columnName: "highIntensityDeceleration",
				expression: "{Deceleration Zone Count: 3 - 4 m/s/s}+{Deceleration Zone Count: > 4 m/s/s}",
				columnLabel: "High Intensity Decel (No)"
			},
			{
				columnName: "highIntensityAcceleration",
				expression: "{Accelerations Zone Count: 3 - 4 m/s/s}+{Accelerations Zone Count: > 4 m/s/s}",
				columnLabel: "High Intensity Accel (No)"
			},
			{
				columnName: "explosiveDistance",
				expression:
					"(({Distance in Power Zone: 25 - 30 w/kg (km)}+{Distance in Power Zone: 30 - 35 w/kg (km)}+{Distance in Power Zone: 35 - 40 w/kg (km)}+{Distance in Power Zone: 40 - 45 w/kg (km)}+{Distance in Power Zone: 45 - 50 w/kg (km)}+{Distance in Power Zone: > 50 w/kg (km)})*1000) - {Sprint Distance (m)}",
				columnLabel: "Explosive Distance (m)"
			},
			{
				columnName: "averageMetabolicPower",
				expression: "{Power Score (w/kg)}",
				columnLabel: "AVG Metabolic Power (W/Kg)"
			},
			{
				columnName: "distancePerMinute",
				expression: "{Distance Per Min (m/min)}",
				columnLabel: "Distance per minute (m)"
			}
		]
	},
	STATSport: {
		rawMetrics: [
			{ name: "Drill Date", label: "Drill Date", type: "number" },
			{ name: "Player Display Name", label: "Player Display Name", type: "number" },
			{ name: "Drill Title", label: "Drill Title", type: "number" },
			{ name: "% Time in Red Zone", label: "% Time in Red Zone", type: "number" },
			{ name: "Accelerations", label: "Accelerations", type: "number" },
			{ name: "Accelerations Z3 to Z6", label: "Accelerations Z3 to Z6", type: "number" },
			{ name: "Accelerations Z4 to Z6", label: "Accelerations Z4 to Z6", type: "number" },
			{ name: "Decelertions Total Distance Z1", label: "Decelertions Total Distance Z1", type: "number" },
			{ name: "Accelerations Z5 to Z6", label: "Accelerations Z5 to Z6", type: "number" },
			{ name: "Acceleration Impulse", label: "Acceleration Impulse", type: "number" },
			{ name: "Distance Z3ToZ6Ab", label: "Distance Z3ToZ6Ab", type: "number" },
			{ name: "Distance Z4ToZ6", label: "Distance Z4ToZ6", type: "number" },
			{ name: "Distance Z2ToZ6Ab", label: "Distance Z2ToZ6Ab", type: "number" },
			{ name: "Acute Vs Chronic Ratio", label: "Acute Vs Chronic Ratio", type: "number" },
			{ name: "Decelertions Total Distance Z3", label: "Decelertions Total Distance Z3", type: "number" },
			{ name: "Time Zone 6 (Relative)", label: "Time Zone 6 (Relative)", type: "number" },
			{ name: "Distance Z5ToZ6Ab", label: "Distance Z5ToZ6Ab", type: "number" },
			{ name: "Distance Z4ToZ6Ab", label: "Distance Z4ToZ6Ab", type: "number" },
			{ name: "Accelerations Zone1", label: "Accelerations Zone1", type: "number" },
			{ name: "Time Zone 6 (Absolute)", label: "Time Zone 6 (Absolute)", type: "number" },
			{ name: "Time Zone 5 (Relative)", label: "Time Zone 5 (Relative)", type: "number" },
			{ name: "Time Zone 5 (Absolute)", label: "Time Zone 5 (Absolute)", type: "number" },
			{ name: "Time Zone 2 (Absolute)", label: "Time Zone 2 (Absolute)", type: "number" },
			{ name: "Decelertions Total Distance Z2", label: "Decelertions Total Distance Z2", type: "number" },
			{ name: "Distance Zone 1 (Relative)", label: "Distance Zone 1 (Relative)", type: "number" },
			{ name: "Distance Z5ToZ6", label: "Distance Z5ToZ6", type: "number" },
			{ name: "Distance Zone 4 (Absolute)", label: "Distance Zone 4 (Absolute)", type: "number" },
			{ name: "Distance Zone 3 (Relative)", label: "Distance Zone 3 (Relative)", type: "number" },
			{ name: "Distance Zone 3 (Absolute)", label: "Distance Zone 3 (Absolute)", type: "number" },
			{ name: "Distance Zone 1 (Absolute)", label: "Distance Zone 1 (Absolute)", type: "number" },
			{ name: "Entries Zone 3 (Absolute)", label: "Entries Zone 3 (Absolute)", type: "number" },
			{ name: "Entries Zone 3 (Relative)", label: "Entries Zone 3 (Relative)", type: "number" },
			{ name: "Entries Zone 4 (Relative)", label: "Entries Zone 4 (Relative)", type: "number" },
			{ name: "Distance Zone 2 (Relative)", label: "Distance Zone 2 (Relative)", type: "number" },
			{ name: "Distance Zone 4 (Relative)", label: "Distance Zone 4 (Relative)", type: "number" },
			{ name: "Time Zone 2 (Relative)", label: "Time Zone 2 (Relative)", type: "number" },
			{ name: "Time Zone 1 (Absolute)", label: "Time Zone 1 (Absolute)", type: "number" },
			{ name: "Time Zone 1 (Relative)", label: "Time Zone 1 (Relative)", type: "number" },
			{ name: "Time Zone 4 (Absolute)", label: "Time Zone 4 (Absolute)", type: "number" },
			{ name: "Time Zone 3 (Relative)", label: "Time Zone 3 (Relative)", type: "number" },
			{ name: "Time Zone 4 (Relative)", label: "Time Zone 4 (Relative)", type: "number" },
			{ name: "Distance Zone 2 (Absolute)", label: "Distance Zone 2 (Absolute)", type: "number" },
			{ name: "Decelertions Total Distance Z4", label: "Decelertions Total Distance Z4", type: "number" },
			{ name: "Entries Zone 4 (Absolute)", label: "Entries Zone 4 (Absolute)", type: "number" },
			{ name: "Decelertions Total Distance Z5", label: "Decelertions Total Distance Z5", type: "number" },
			{ name: "Decelertions Total Distance Z6", label: "Decelertions Total Distance Z6", type: "number" },
			{ name: "Distance Z2ToZ6", label: "Distance Z2ToZ6", type: "number" },
			{ name: "Distance Z3ToZ6", label: "Distance Z3ToZ6", type: "number" },
			{ name: "Accelertions Total Distance Z5", label: "Accelertions Total Distance Z5", type: "number" },
			{ name: "Accelertions Total Distance Z2", label: "Accelertions Total Distance Z2", type: "number" },
			{ name: "Accelertions Total Distance Z6", label: "Accelertions Total Distance Z6", type: "number" },
			{ name: "Total Time", label: "Total Time", type: "number" },
			{ name: "Accelertions Total Distance Z1", label: "Accelertions Total Distance Z1", type: "number" },
			{ name: "Accelertions Total Distance Z4", label: "Accelertions Total Distance Z4", type: "number" },
			{ name: "Total Loading", label: "Total Loading", type: "number" },
			{ name: "HML Distance", label: "HML Distance", type: "number" },
			{ name: "Accelertions Total Distance Z3", label: "Accelertions Total Distance Z3", type: "number" },
			{ name: "Session Type", label: "Session Type", type: "number" },
			{ name: "Time Zone 3 (Absolute)", label: "Time Zone 3 (Absolute)", type: "number" },
			{ name: "Accelerations Zone2", label: "Accelerations Zone2", type: "number" },
			{ name: "Drill End Time", label: "Drill End Time", type: "number" },
			{ name: "Player Position", label: "Player Position", type: "number" },
			{ name: "Total Right Steps", label: "Total Right Steps", type: "number" },
			{ name: "Total Left Steps", label: "Total Left Steps", type: "number" },
			{ name: "Time In Heart Rate Zone2", label: "Time In Heart Rate Zone2", type: "number" },
			{ name: "Session Date", label: "Session Date", type: "number" },
			{ name: "Time In Red Zone", label: "Time In Red Zone", type: "number" },
			{ name: "Total Deceleration Loading", label: "Total Deceleration Loading", type: "number" },
			{ name: "Right Vertical Impact", label: "Right Vertical Impact", type: "number" },
			{ name: "Drill Start Time", label: "Drill Start Time", type: "number" },
			{ name: "Right Mag Impact", label: "Right Mag Impact", type: "number" },
			{ name: "Right Lateral Impact", label: "Right Lateral Impact", type: "number" },
			{ name: "Right Ant Post Impact", label: "Right Ant Post Impact", type: "number" },
			{ name: "Player Weight", label: "Player Weight", type: "number" },
			{ name: "Right Average Vert Impact", label: "Right Average Vert Impact", type: "number" },
			{ name: "Player Height", label: "Player Height", type: "number" },
			{ name: "Impacts", label: "Impacts", type: "number" },
			{ name: "Mood", label: "Mood", type: "number" },
			{ name: "Player Name", label: "Player Name", type: "number" },
			{ name: "Osmolarity", label: "Osmolarity", type: "number" },
			{ name: "Player Date Of Birth", label: "Player Date Of Birth", type: "number" },
			{ name: "Player Max Heart Rate [From Profile]", label: "Player Max Heart Rate [From Profile]", type: "number" },
			{ name: "Player First Name", label: "Player First Name", type: "number" },
			{ name: "Number of High Intensity Bursts", label: "Number of High Intensity Bursts", type: "number" },
			{ name: "Player Last Name", label: "Player Last Name", type: "number" },
			{ name: "Player Id", label: "Player Id", type: "number" },
			{ name: "Perceived Exertion", label: "Perceived Exertion", type: "number" },
			{ name: "HSR Per Minute (Relative)", label: "HSR Per Minute (Relative)", type: "number" },
			{ name: "Drill Id", label: "Drill Id", type: "number" },
			{ name: "Dynamic Stress Load Z3 to Z6", label: "Dynamic Stress Load Z3 to Z6", type: "number" },
			{ name: "HML Time", label: "HML Time", type: "number" },
			{ name: "Accelerations Zone3", label: "Accelerations Zone3", type: "number" },
			{ name: "Accelerations Zone4", label: "Accelerations Zone4", type: "number" },
			{ name: "Accelerations Zone5", label: "Accelerations Zone5", type: "number" },
			{ name: "Dynamic Stress Load Zone2", label: "Dynamic Stress Load Zone2", type: "number" },
			{ name: "Sleep", label: "Sleep", type: "number" },
			{ name: "Time In Heart Rate Z3 to Z6", label: "Time In Heart Rate Z3 to Z6", type: "number" },
			{ name: "Time In Heart Rate Zone6", label: "Time In Heart Rate Zone6", type: "number" },
			{ name: "Session Week Number", label: "Session Week Number", type: "number" },
			{ name: "Time In Heart Rate Zone1", label: "Time In Heart Rate Zone1", type: "number" },
			{ name: "Session Title", label: "Session Title", type: "number" },
			{ name: "Time In Heart Rate Zone4", label: "Time In Heart Rate Zone4", type: "number" },
			{ name: "Session Day of Week", label: "Session Day of Week", type: "number" },
			{ name: "Speed Intensity Zone5", label: "Speed Intensity Zone5", type: "number" },
			{ name: "Session End Time", label: "Session End Time", type: "number" },
			{ name: "Time In Heart Rate Zone3", label: "Time In Heart Rate Zone3", type: "number" },
			{ name: "Accelerations Zone6", label: "Accelerations Zone6", type: "number" },
			{ name: "Time In Heart Rate Zone5", label: "Time In Heart Rate Zone5", type: "number" },
			{ name: "Soreness", label: "Soreness", type: "number" },
			{ name: "Step Balance", label: "Step Balance", type: "number" },
			{ name: "HML Distance Per Minute", label: "HML Distance Per Minute", type: "number" },
			{ name: "Sprint Distance", label: "Sprint Distance", type: "number" },
			{ name: "Stress", label: "Stress", type: "number" },
			{ name: "Time In Heart Rate Z4 to Z6", label: "Time In Heart Rate Z4 to Z6", type: "number" },
			{ name: "Speed Intensity Zone2", label: "Speed Intensity Zone2", type: "number" },
			{ name: "Speed Intensity Zone3", label: "Speed Intensity Zone3", type: "number" },
			{ name: "Sprints", label: "Sprints", type: "number" },
			{ name: "Speed Intensity Zone4", label: "Speed Intensity Zone4", type: "number" },
			{ name: "Speed Intensity", label: "Speed Intensity", type: "number" },
			{ name: "Speed Intensity Z3 to Z6", label: "Speed Intensity Z3 to Z6", type: "number" },
			{ name: "Speed Intensity Z4 to Z6", label: "Speed Intensity Z4 to Z6", type: "number" },
			{ name: "Session Id", label: "Session Id", type: "number" },
			{ name: "Metabolic Time Zone 6", label: "Metabolic Time Zone 6", type: "number" },
			{ name: "Speed Intensity Zone1", label: "Speed Intensity Zone1", type: "number" },
			{ name: "Speed Intensity Z5 to Z6", label: "Speed Intensity Z5 to Z6", type: "number" },
			{ name: "Session Start Time", label: "Session Start Time", type: "number" },
			{ name: "Entries Zone 5 (Absolute)", label: "Entries Zone 5 (Absolute)", type: "number" },
			{ name: "Max Speed", label: "Max Speed", type: "number" },
			{ name: "Metabolic Time Zone 5", label: "Metabolic Time Zone 5", type: "number" },
			{ name: "Speed Intensity Zone6", label: "Speed Intensity Zone6", type: "number" },
			{ name: "Impacts Z4 to Z6", label: "Impacts Z4 to Z6", type: "number" },
			{ name: "Impacts Zone4", label: "Impacts Zone4", type: "number" },
			{ name: "Metabolic Time Zonal", label: "Metabolic Time Zonal", type: "number" },
			{ name: "Impacts Zone5", label: "Impacts Zone5", type: "number" },
			{ name: "Metabolic Distance Zonal", label: "Metabolic Distance Zonal", type: "number" },
			{ name: "Metabolic Time Zone 2", label: "Metabolic Time Zone 2", type: "number" },
			{ name: "Metabolic Time Zone 1", label: "Metabolic Time Zone 1", type: "number" },
			{ name: "Metabolic Time Zone 4", label: "Metabolic Time Zone 4", type: "number" },
			{ name: "Example", label: "Example", type: "number" },
			{ name: "Left Vertical Impact", label: "Left Vertical Impact", type: "number" },
			{ name: "Left Ant Post Impact", label: "Left Ant Post Impact", type: "number" },
			{ name: "Metabolic Distance Zone 4", label: "Metabolic Distance Zone 4", type: "number" },
			{ name: "Metabolic Time Zone 3", label: "Metabolic Time Zone 3", type: "number" },
			{ name: "Impacts Zone2", label: "Impacts Zone2", type: "number" },
			{ name: "Metabolic Distance Zone 6", label: "Metabolic Distance Zone 6", type: "number" },
			{ name: "Metabolic Distance Zone 2", label: "Metabolic Distance Zone 2", type: "number" },
			{ name: "Metabolic Distance Zone 5", label: "Metabolic Distance Zone 5", type: "number" },
			{ name: "Max Heart Rate", label: "Max Heart Rate", type: "number" },
			{ name: "Metabolic Distance Zone 3", label: "Metabolic Distance Zone 3", type: "number" },
			{ name: "Metabolic Distance Zone 1", label: "Metabolic Distance Zone 1", type: "number" },
			{ name: "Left Average Vert Impact", label: "Left Average Vert Impact", type: "number" },
			{ name: "Left Mag Impact", label: "Left Mag Impact", type: "number" },
			{ name: "Max Acceleration", label: "Max Acceleration", type: "number" },
			{ name: "Max Deceleration", label: "Max Deceleration", type: "number" },
			{ name: "Lower Speed Loading", label: "Lower Speed Loading", type: "number" },
			{ name: "Left Lateral Impact", label: "Left Lateral Impact", type: "number" },
			{ name: "Interval", label: "Interval", type: "number" },
			{ name: "Impacts Zone6", label: "Impacts Zone6", type: "number" },
			{ name: "Impacts Zone3", label: "Impacts Zone3", type: "number" },
			{ name: "Impacts Z5 to Z6", label: "Impacts Z5 to Z6", type: "number" },
			{ name: "Fatigue Index", label: "Fatigue Index", type: "number" },
			{ name: "Impacts Z3 to Z6", label: "Impacts Z3 to Z6", type: "number" },
			{ name: "Impacts Zone1", label: "Impacts Zone1", type: "number" },
			{ name: "Average Heart Rate", label: "Average Heart Rate", type: "number" },
			{ name: "Entries Zone 6 (Absolute)", label: "Entries Zone 6 (Absolute)", type: "number" },
			{ name: "HSR Per Minute (Absolute)", label: "HSR Per Minute (Absolute)", type: "number" },
			{ name: "Fatigue", label: "Fatigue", type: "number" },
			{ name: "Equivalent Metabolic Distance", label: "Equivalent Metabolic Distance", type: "number" },
			{ name: "Entries Zone 6 (Relative)", label: "Entries Zone 6 (Relative)", type: "number" },
			{ name: "Heart Rate Recovery Percent", label: "Heart Rate Recovery Percent", type: "number" },
			{ name: "Heart Rate Recovery Beats", label: "Heart Rate Recovery Beats", type: "number" },
			{ name: "HML Efforts", label: "HML Efforts", type: "number" },
			{ name: "High Speed Running (Absolute)", label: "High Speed Running (Absolute)", type: "number" },
			{ name: "EqD-td", label: "EqD-td", type: "number" },
			{ name: "High Speed Running (Relative)", label: "High Speed Running (Relative)", type: "number" },
			{ name: "Explosive Distance", label: "Explosive Distance", type: "number" },
			{ name: "Heart Rate Variability", label: "Heart Rate Variability", type: "number" },
			{ name: "Heart Rate Exertion", label: "Heart Rate Exertion", type: "number" },
			{ name: "Dynamic Stress Load Zone6", label: "Dynamic Stress Load Zone6", type: "number" },
			{ name: "Dynamic Stress Load Zone3", label: "Dynamic Stress Load Zone3", type: "number" },
			{ name: "Dynamic Stress Load Zone4", label: "Dynamic Stress Load Zone4", type: "number" },
			{ name: "Dynamic Stress Load Zone5", label: "Dynamic Stress Load Zone5", type: "number" },
			{ name: "Dynamic Stress Load", label: "Dynamic Stress Load", type: "number" },
			{ name: "Dynamic Stress Load Z4 to Z6", label: "Dynamic Stress Load Z4 to Z6", type: "number" },
			{ name: "Dynamic Stress Load Zone1", label: "Dynamic Stress Load Zone1", type: "number" },
			{ name: "Entries Zone 5 (Relative)", label: "Entries Zone 5 (Relative)", type: "number" },
			{ name: "Dynamic Stress Load Z5 to Z6", label: "Dynamic Stress Load Z5 to Z6", type: "number" },
			{ name: "Duration of High Intensity Bursts", label: "Duration of High Intensity Bursts", type: "number" },
			{ name: "Average Metabolic Power", label: "Average Metabolic Power", type: "number" },
			{ name: "Average Speed", label: "Average Speed", type: "number" },
			{ name: "Energy Expenditure (KCal)", label: "Energy Expenditure (KCal)", type: "number" },
			{ name: "Custom Metric 2", label: "Custom Metric 2", type: "number" },
			{ name: "Custom Metric 3", label: "Custom Metric 3", type: "number" },
			{ name: "Custom Metric 4", label: "Custom Metric 4", type: "number" },
			{ name: "Custom Metric 5", label: "Custom Metric 5", type: "number" },
			{ name: "Custom Metric 6", label: "Custom Metric 6", type: "number" },
			{ name: "Custom Metric 7", label: "Custom Metric 7", type: "number" },
			{ name: "Custom Metric 8", label: "Custom Metric 8", type: "number" },
			{ name: "Custom Metric 9", label: "Custom Metric 9", type: "number" },
			{ name: "Custom Metric 10", label: "Custom Metric 10", type: "number" },
			{ name: "Custom Player Id", label: "Custom Player Id", type: "number" },
			{ name: "Distance Zone 5 (Absolute)", label: "Distance Zone 5 (Absolute)", type: "number" },
			{ name: "Distance Zone 6 (Absolute)", label: "Distance Zone 6 (Absolute)", type: "number" },
			{ name: "Distance Zone 5 (Relative)", label: "Distance Zone 5 (Relative)", type: "number" },
			{ name: "Distance Zone 6 (Relative)", label: "Distance Zone 6 (Relative)", type: "number" },
			{ name: "Distance Zonal", label: "Distance Zonal", type: "number" },
			{ name: "Distance Total", label: "Distance Total", type: "number" },
			{ name: "Distance Per Min", label: "Distance Per Min", type: "number" },
			{ name: "Decelerations Zone6", label: "Decelerations Zone6", type: "number" },
			{ name: "Decelerations Zone5", label: "Decelerations Zone5", type: "number" },
			{ name: "Decelerations Zone3", label: "Decelerations Zone3", type: "number" },
			{ name: "Decelerations Zone4", label: "Decelerations Zone4", type: "number" },
			{ name: "Decelerations Zone2", label: "Decelerations Zone2", type: "number" },
			{ name: "Decelerations Zone1", label: "Decelerations Zone1", type: "number" },
			{ name: "Decelerations", label: "Decelerations", type: "number" },
			{ name: "Deceleration Z3 to Z6", label: "Deceleration Z3 to Z6", type: "number" },
			{ name: "Deceleration Z4 to Z6", label: "Deceleration Z4 to Z6", type: "number" },
			{ name: "Deceleration Z5 to Z6", label: "Deceleration Z5 to Z6", type: "number" }
		],
		splitNameColumn: "Drill Title",
		dateColumn: "Drill Date",
		dateColumnFormat: 2,
		startTimeColumn: "Drill Start Time",
		startTimeColumnFormat: 5,
		endTimeColumn: "Drill End Time",
		endTimeColumnFormat: 5,
		playerNameColumn: "Player Display Name",
		durationColumn: null,
		durationColumnFormat: null,
		_gpsMetricsMapping: [
			{
				columnName: "rpe",
				expression: null,
				columnLabel: "RPE"
			},
			{
				columnName: "rpeTl",
				expression: null,
				columnLabel: "RPE TL"
			},
			{
				columnName: "heartRate85to90",
				expression: "{Time In Heart Rate Zone2}",
				columnLabel: "HR 85-90 (min)"
			},
			{
				columnName: "heartRateGr90",
				expression: "({Time In Heart Rate Zone3}+{Time In Heart Rate Zone4}+{Time In Heart Rate Zone5}+{Time In Heart Rate Zone6})",
				columnLabel: "HR >90 (min)"
			},
			{
				columnName: "totalDistance",
				expression: "{Distance Total}",
				columnLabel: "Total Distance (Km)"
			},
			{
				columnName: "sprintDistance",
				expression: "{Distance Zone 6 (Absolute)}",
				columnLabel: "Sprint Distance (m)"
			},
			{
				columnName: "highspeedRunningDistance",
				expression: "{High Speed Running (Absolute)}",
				columnLabel: "High Speed Running Distance (m)"
			},
			{
				columnName: "powerDistance",
				expression: "{Metabolic Distance Zonal}",
				columnLabel: "Power Distance (m)"
			},
			{
				columnName: "highPowerDistance",
				expression: "{HML Distance}",
				columnLabel: "High Power Distance (m)"
			},
			{
				columnName: "powerPlays",
				expression: "{HML Efforts}",
				columnLabel: "Power Plays (No)"
			},
			{
				columnName: "highIntensityDeceleration",
				expression: "{Deceleration Z4 to Z6}",
				columnLabel: "High Intensity Decel (No)"
			},
			{
				columnName: "highIntensityAcceleration",
				expression: "{Accelerations Z4 to Z6}",
				columnLabel: "High Intensity Accel (No)"
			},
			{
				columnName: "explosiveDistance",
				expression: "{Explosive Distance}",
				columnLabel: "Explosive Distance (m)"
			},
			{
				columnName: "averageMetabolicPower",
				expression: "{Average Metabolic Power}",
				columnLabel: "AVG Metabolic Power (W/Kg)"
			},
			{
				columnName: "distancePerMinute",
				expression: "{Distance Per Min}",
				columnLabel: "Distance per minute (m)"
			}
		]
	}
};
