export default {
	InStat: {
		rawMetrics: [
			{ name: "KIT NUMBER", label: "KIT NUMBER", type: "number" },
			{ name: "SURNAME", label: "SURNAME", type: "number" },
			{ name: "TEAM", label: "TEAM", type: "number" },
			{ name: "MATCH", label: "MATCH", type: "number" },
			{ name: "MATCH DATE", label: "MATCH DATE", type: "number" },
			{ name: "PLAYER'S POSITION", label: "PLAYER'S POSITION", type: "number" },
			{ name: "INSTAT INDEX", label: "INSTAT INDEX", type: "number" },
			{ name: "GOALS", label: "GOALS", type: "number" },
			{ name: "ASSISTS", label: "ASSISTS", type: "number" },
			{ name: "PLAYING IN SCORING ATTACKS", label: "PLAYING IN SCORING ATTACKS", type: "number" },
			{ name: "GRAVE MISTAKES", label: "GRAVE MISTAKES", type: "number" },
			{ name: "YELLOW CARDS", label: "YELLOW CARDS", type: "number" },
			{ name: "RED CARDS", label: "RED CARDS", type: "number" },
			{ name: "FOUL", label: "FOUL", type: "number" },
			{ name: "FOUL SUFFERED", label: "FOUL SUFFERED", type: "number" },
			{ name: "SHOTS", label: "SHOTS", type: "number" },
			{ name: "SHOTS / ON TARGET", label: "SHOTS / ON TARGET", type: "number" },
			{ name: "PASSES", label: "PASSES", type: "number" },
			{ name: "PASSES ACCURATE", label: "PASSES ACCURATE", type: "number" },
			{ name: "% OF ACCURATE PASSES", label: "% OF ACCURATE PASSES", type: "number" },
			{ name: "EXTRA ATTACKING AND KEY PASSES", label: "EXTRA ATTACKING AND KEY PASSES", type: "number" },
			{ name: "EXTRA ATTACKING AND KEY PASSES - ACCURATE", label: "EXTRA ATTACKING AND KEY PASSES - ACCURATE", type: "number" },
			{ name: "CROSSES", label: "CROSSES", type: "number" },
			{ name: "CROSSES - ACCURATE", label: "CROSSES - ACCURATE", type: "number" },
			{ name: "CROSSES - ACCURATE, %", label: "CROSSES - ACCURATE, %", type: "number" },
			{ name: "CHALLENGES", label: "CHALLENGES", type: "number" },
			{ name: "CHALLENGES / WON", label: "CHALLENGES / WON", type: "number" },
			{ name: "% OF CHALLENGES WON", label: "% OF CHALLENGES WON", type: "number" },
			{ name: "DEFENSIVE CHALLENGES", label: "DEFENSIVE CHALLENGES", type: "number" },
			{ name: "DEFENSIVE CHALLENGES SUCCESSFUL", label: "DEFENSIVE CHALLENGES SUCCESSFUL", type: "number" },
			{ name: "CHALLENGES IN DEFENCE / WON, %", label: "CHALLENGES IN DEFENCE / WON, %", type: "number" },
			{ name: "ATTACKING CHALLENGES", label: "ATTACKING CHALLENGES", type: "number" },
			{ name: "ATTACKING CHALLENGES SUCCESSFUL", label: "ATTACKING CHALLENGES SUCCESSFUL", type: "number" },
			{ name: "CHALLENGES IN ATTACK / WON, %", label: "CHALLENGES IN ATTACK / WON, %", type: "number" },
			{ name: "AIR CHALLENGES", label: "AIR CHALLENGES", type: "number" },
			{ name: "AIR CHALLENGES / WON", label: "AIR CHALLENGES / WON", type: "number" },
			{ name: "AIR CHALLENGES, %", label: "AIR CHALLENGES, %", type: "number" },
			{ name: "DRIBBLES", label: "DRIBBLES", type: "number" },
			{ name: "DRIBBLES SUCCESSFUL", label: "DRIBBLES SUCCESSFUL", type: "number" },
			{ name: "% OF SUCCESSFULL DRIBBLES", label: "% OF SUCCESSFULL DRIBBLES", type: "number" },
			{ name: "TACKLES", label: "TACKLES", type: "number" },
			{ name: "TACKLES SUCCESSFUL", label: "TACKLES SUCCESSFUL", type: "number" },
			{ name: "% OF TACKLES WON", label: "% OF TACKLES WON", type: "number" },
			{ name: "INTERCEPTIONS", label: "INTERCEPTIONS", type: "number" },
			{ name: "INTERCEPTIONS / IN OPP_ HALF", label: "INTERCEPTIONS / IN OPP_ HALF", type: "number" },
			{ name: "PICKING UP FREE BALLS", label: "PICKING UP FREE BALLS", type: "number" },
			{ name: "PICKING UP FREE BALLS IN OPP_ HALF", label: "PICKING UP FREE BALLS IN OPP_ HALF", type: "number" },
			{ name: "LOST BALLS", label: "LOST BALLS", type: "number" },
			{ name: "LOST BALLS / IN OWN HALF", label: "LOST BALLS / IN OWN HALF", type: "number" },
			{ name: "RECOVERED BALLS", label: "RECOVERED BALLS", type: "number" },
			{ name: "RECOVERED BALLS / IN OPP_ HALF", label: "RECOVERED BALLS / IN OPP_ HALF", type: "number" },
			{ name: "PASSES FORWARD (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES FORWARD (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES BACK (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES BACK (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE LEFT (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE LEFT (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE RIGHT (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE RIGHT (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES FORWARD ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES FORWARD ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES BACK ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES BACK ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE LEFT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE LEFT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "PASSES TO THE RIGHT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", label: "PASSES TO THE RIGHT ACCURATE (CAPTURE ANGLE - 180 DEGREES)", type: "number" },
			{ name: "MINUTES PLAYED", label: "MINUTES PLAYED", type: "number" },
			{ name: "GOALKEEPERS - GOALS CONCEDED", label: "GOALKEEPERS - GOALS CONCEDED", type: "number" },
			{ name: "GOALKEEPERS - SHOTS", label: "GOALKEEPERS - SHOTS", type: "number" },
			{ name: "GOALKEEPERS - SHOTS SAVED", label: "GOALKEEPERS - SHOTS SAVED", type: "number" },
			{ name: "GOALKEEPERS - SHOTS TAKEN, %", label: "GOALKEEPERS - SHOTS TAKEN, %", type: "number" },
			{ name: "GOALKEEPER SAVES", label: "GOALKEEPER SAVES", type: "number" },
			{ name: "FOULS - PENALTIES", label: "FOULS - PENALTIES", type: "number" },
			{ name: "GOALKEEPER'S - INTERCEPTION", label: "GOALKEEPER'S - INTERCEPTION", type: "number" },
			{ name: "GOOD INTERCEPTION OF GOALKEEPER", label: "GOOD INTERCEPTION OF GOALKEEPER", type: "number" },
			{ name: "RECEIVED PASSES", label: "RECEIVED PASSES", type: "number" },
			{ name: "LONG PASSES", label: "LONG PASSES", type: "number" },
			{ name: "LONG PASSES - ACCURATE", label: "LONG PASSES - ACCURATE", type: "number" }
		],
		splitField: "TEAM",
		playerField: "SURNAME",
		durationField: "MINUTES PLAYED",
		yellowCardField: "YELLOW CARDS",
		redCardField: "RED CARDS",
		substituteInMinuteField: null,
		substituteOutMinuteField: null
	},
	PaniniDigital: {
		rawMetrics: [
			{ name: "Squadra", label: "Squadra", type: "number" },
			{ name: "ID Giocatore", label: "ID Giocatore", type: "number" },
			{ name: "Nome", label: "Nome", type: "number" },
			{ name: "Cognome", label: "Cognome", type: "number" },
			{ name: "Alias", label: "Alias", type: "number" },
			{ name: "Numero", label: "Numero", type: "number" },
			{ name: "Ruolo", label: "Ruolo", type: "number" },
			{ name: "Titolare/Riserva", label: "Titolare/Riserva", type: "number" },
			{ name: "Presenze", label: "Presenze", type: "number" },
			{ name: "Minuti di gioco", label: "Minuti di gioco", type: "number" },
			{ name: "Ammonizioni", label: "Ammonizioni", type: "number" },
			{ name: "Espulsioni", label: "Espulsioni", type: "number" },
			{ name: "Palle giocate", label: "Palle giocate", type: "number" },
			{ name: "Passaggi tentati", label: "Passaggi tentati", type: "number" },
			{ name: "Passaggi riusciti", label: "Passaggi riusciti", type: "number" },
			{ name: "Giocate utili", label: "Giocate utili", type: "number" },
			{ name: "Passaggi lunghi", label: "Passaggi lunghi", type: "number" },
			{ name: "Cambi di gioco", label: "Cambi di gioco", type: "number" },
			{ name: "Cross su azione", label: "Cross su azione", type: "number" },
			{ name: "Passaggi filtranti utili", label: "Passaggi filtranti utili", type: "number" },
			{ name: "Dribbling utili", label: "Dribbling utili", type: "number" },
			{ name: "Assist", label: "Assist", type: "number" },
			{ name: "Assist vincenti", label: "Assist vincenti", type: "number" },
			{ name: "Tiri", label: "Tiri", type: "number" },
			{ name: "Tiri dentro", label: "Tiri dentro", type: "number" },
			{ name: "Reti", label: "Reti", type: "number" },
			{ name: "Occasioni", label: "Occasioni", type: "number" },
			{ name: "Angoli", label: "Angoli", type: "number" },
			{ name: "Angoli da destra", label: "Angoli da destra", type: "number" },
			{ name: "Angoli da sinistra", label: "Angoli da sinistra", type: "number" },
			{ name: "Punizioni in attacco", label: "Punizioni in attacco", type: "number" },
			{ name: "Contrasti", label: "Contrasti", type: "number" },
			{ name: "Contrasti effettivi", label: "Contrasti effettivi", type: "number" },
			{ name: "Palle recuperate", label: "Palle recuperate", type: "number" },
			{ name: "Palle recuperate effettive", label: "Palle recuperate effettive", type: "number" },
			{ name: "Intercettazioni", label: "Intercettazioni", type: "number" },
			{ name: "Intercettazioni effettive", label: "Intercettazioni effettive", type: "number" },
			{ name: "Anticipi", label: "Anticipi", type: "number" },
			{ name: "Anticipi effettivi", label: "Anticipi effettivi", type: "number" },
			{ name: "Duelli aerei vinti", label: "Duelli aerei vinti", type: "number" },
			{ name: "Palle perse", label: "Palle perse", type: "number" }
		],
		splitField: "Squadra",
		playerField: "Cognome",
		durationField: "Minuti di gioco",
		yellowCardField: "Ammonizioni",
		redCardField: "Espulsioni",
		substituteInMinuteField: null,
		substituteOutMinuteField: null
	}
};
