export default {
	technical: [
		{ title: 'profile.attributes.passing', name: 'passing', tooltip: 'profile.attributes.passing.tooltip'},
		{ title: 'profile.attributes.first_touch', name: 'first_touch', tooltip: 'profile.attributes.first_touch.tooltip'},
		{ title: 'profile.attributes.long_shots', name: 'long_shots', tooltip: 'profile.attributes.long_shots.tooltip'},
		{ title: 'profile.attributes.finishing', name: 'finishing', tooltip: 'profile.attributes.finishing.tooltip'},
		{ title: 'profile.attributes.dribbling', name: 'dribbling', tooltip: 'profile.attributes.dribbling.tooltip'},
		{ title: 'profile.attributes.technique', name: 'technique', tooltip: 'profile.attributes.technique.tooltip'},
		{ title: 'profile.attributes.heading', name: 'heading', tooltip: 'profile.attributes.heading.tooltip'},
		{ title: 'profile.attributes.crossing', name: 'crossing', tooltip: 'profile.attributes.crossing.tooltip'},
		{ title: 'profile.attributes.tackling', name: 'tackling', tooltip: 'profile.attributes.tackling.tooltip'},
		{ title: 'profile.attributes.marking', name: 'marking', tooltip: 'profile.attributes.marking.tooltip'},
		{ title: 'profile.attributes.corners', name: 'corners', tooltip: 'profile.attributes.corners.tooltip'},
		{ title: 'profile.attributes.free_kicks', name: 'free_kicks', tooltip: 'profile.attributes.free_kicks.tooltip'},
		{ title: 'profile.attributes.long_throws', name: 'long_throws', tooltip: 'profile.attributes.long_throws.tooltip'},
		{ title: 'profile.attributes.penalty', name: 'penalty', tooltip: 'profile.attributes.penalty.tooltip'}
	],
	attitude: [
		{ title: 'profile.attributes.anticipation', name: 'anticipation', tooltip: 'profile.attributes.anticipation.tooltip'},
		{ title: 'profile.attributes.aggression', name: 'aggression', tooltip: 'profile.attributes.aggression.tooltip'},
		{ title: 'profile.attributes.concentration', name: 'concentration', tooltip: 'profile.attributes.concentration.tooltip'},
		{ title: 'profile.attributes.decision', name: 'decision', tooltip: 'profile.attributes.decision.tooltip'},
		{ title: 'profile.attributes.flair', name: 'flair', tooltip: 'profile.attributes.flair.tooltip'},
		{ title: 'profile.attributes.leadership', name: 'leadership', tooltip: 'profile.attributes.leadership.tooltip'},
		{ title: 'profile.attributes.teamwork', name: 'teamwork', tooltip: 'profile.attributes.teamwork.tooltip'},
		{ title: 'profile.attributes.vision', name: 'vision', tooltip: 'profile.attributes.vision.tooltip'},
		{ title: 'profile.attributes.composure', name: 'composure', tooltip: 'profile.attributes.composure.tooltip'},
		{ title: 'profile.attributes.determination', name: 'determination', tooltip: 'profile.attributes.determination.tooltip'},
		{ title: 'profile.attributes.bravery', name: 'bravery', tooltip: 'profile.attributes.bravery.tooltip'},
		{ title: 'profile.attributes.positioning', name: 'positioning', tooltip: 'profile.attributes.positioning.tooltip'},
		{ title: 'profile.attributes.off_the_ball', name: 'off_the_ball', tooltip: 'profile.attributes.off_the_ball.tooltip'},
		{ title: 'profile.attributes.workrate', name: 'workrate', tooltip: 'profile.attributes.workrate.tooltip'}
	],
	offensive: [
		{ title: 'profile.attributes.offensive_org', name: '_offensive_organization'},
		{ title: 'profile.attributes.offensive_trans', name: '_offensive_transition'},
		{ title: 'profile.attributes.offensive_set_pieces', name: '_offensive_setPieces'},
	],
	defensive: [
		{ title: 'profile.attributes.defensive_org', name: '_defensive_organization'},
		{ title: 'profile.attributes.defensive_trans', name: '_defensive_transition'},
		{ title: 'profile.attributes.defensive_setPieces', name: '_defensive_setPieces'},
	],
	positives: [
		{label: "profile.attributes.personality.modelCitizen", value: "modelCitizen", tooltip: "profile.attributes.personality.modelCitizen.tooltip"},
		{label: "profile.attributes.personality.perfectionist", value: "perfectionist", tooltip: "profile.attributes.personality.perfectionist.tooltip"},
		{label: "profile.attributes.personality.resolute", value: "resolute", tooltip: "profile.attributes.personality.resolute.tooltip"},
		{label: "profile.attributes.personality.modelProfessional", value: "modelProfessional", tooltip: "profile.attributes.personality.modelProfessional.tooltip"},
		{label: "profile.attributes.personality.professional", value: "professional", tooltip: "profile.attributes.personality.professional.tooltip"},
		{label: "profile.attributes.personality.fairlyProfessional", value: "fairlyProfessional", tooltip: "profile.attributes.personality.fairlyProfessional.tooltip"},
		{label: "profile.attributes.personality.spirited", value: "spirited", tooltip: "profile.attributes.personality.spirited.tooltip"},
		{label: "profile.attributes.personality.veryAmbitious", value: "veryAmbitious", tooltip: "profile.attributes.personality.veryAmbitious.tooltip"},
		{label: "profile.attributes.personality.ambitious", value: "ambitious", tooltip: "profile.attributes.personality.ambitious.tooltip"},
		{label: "profile.attributes.personality.driven", value: "driven", tooltip: "profile.attributes.personality.driven.tooltip"},
		{label: "profile.attributes.personality.determined", value: "determined", tooltip: "profile.attributes.personality.determined.tooltip"},
		{label: "profile.attributes.personality.fairlyDetermined", value: "fairlyDetermined", tooltip: "profile.attributes.personality.fairlyDetermined.tooltip"},
		{label: "profile.attributes.personality.charismaticLeader", value: "charismaticLeader", tooltip: "profile.attributes.personality.charismaticLeader.tooltip"},
		{label: "profile.attributes.personality.bornLeader", value: "bornLeader", tooltip: "profile.attributes.personality.bornLeader.tooltip"},
		{label: "profile.attributes.personality.leader", value: "leader", tooltip: "profile.attributes.personality.leader.tooltip"},
		{label: "profile.attributes.personality.ironWiled", value: "ironWiled", tooltip: "profile.attributes.personality.ironWiled.tooltip"},
		{label: "profile.attributes.personality.resilient", value: "resilient", tooltip: "profile.attributes.personality.resilient.tooltip"}
	],
	negatives: [
		{label: "profile.attributes.personality.slack", value: "slack", tooltip: "profile.attributes.personality.slack.tooltip"},
		{label: "profile.attributes.personality.causal", value: "causal", tooltip: "profile.attributes.personality.causal.tooltip"},
		{label: "profile.attributes.personality.temperamental", value: "temperamental", tooltip: "profile.attributes.personality.temperamental.tooltip"},
		{label: "profile.attributes.personality.unambitious", value: "unambitious", tooltip: "profile.attributes.personality.unambitious.tooltip"},
		{label: "profile.attributes.personality.easilyDiscouraged", value: "easilyDiscouraged", tooltip: "profile.attributes.personality.easilyDiscouraged.tooltip"},
		{label: "profile.attributes.personality.lowDetermination", value: "lowDetermination", tooltip: "profile.attributes.personality.lowDetermination.tooltip"},
		{label: "profile.attributes.personality.spineless", value: "spineless", tooltip: "profile.attributes.personality.spineless.tooltip"},
		{label: "profile.attributes.personality.lowSelfBelief", value: "lowSelfBelief", tooltip: "profile.attributes.personality.lowSelfBelief.tooltip"}
	],
	neutrals: [
		{label: "profile.attributes.personality.jovial", value: "jovial", tooltip: "profile.attributes.personality.jovial.tooltip"},
		{label: "profile.attributes.personality.lightHearted", value: "lightHearted", tooltip: "profile.attributes.personality.lightHearted.tooltip"},
		{label: "profile.attributes.personality.devoted", value: "devoted", tooltip: "profile.attributes.personality.devoted.tooltip"},
		{label: "profile.attributes.personality.loyal", value: "loyal", tooltip: "profile.attributes.personality.loyal.tooltip"},
		{label: "profile.attributes.personality.fairlyLoyal", value: "fairlyLoyal", tooltip: "profile.attributes.personality.fairlyLoyal.tooltip"},
		{label: "profile.attributes.personality.honest", value: "honest", tooltip: "profile.attributes.personality.honest.tooltip"},
		{label: "profile.attributes.personality.sporting", value: "sporting", tooltip: "profile.attributes.personality.sporting.tooltip"},
		{label: "profile.attributes.personality.fairlySporting", value: "fairlySporting", tooltip: "profile.attributes.personality.fairlySporting.tooltip"},
		{label: "profile.attributes.personality.unsporting", value: "unsporting", tooltip: "profile.attributes.personality.unsporting.tooltip"},
		{label: "profile.attributes.personality.realist", value: "realist", tooltip: "profile.attributes.personality.realist.tooltip"},
		{label: "profile.attributes.personality.balanced", value: "balanced", tooltip: "profile.attributes.personality.balanced.tooltip"}
	],
	medias: [
		{label: "profile.attributes.personality.confrontational", value: "confrontational", tooltip: "profile.attributes.personality.confrontational.tooltip"},
		{label: "profile.attributes.personality.evasive", value: "evasive", tooltip: "profile.attributes.personality.evasive.tooltip"},
		{label: "profile.attributes.personality.levelHeaded", value: "levelHeaded", tooltip: "profile.attributes.personality.levelHeaded.tooltip"},
		{label: "profile.attributes.personality.mediaFriendly", value: "mediaFriendly", tooltip: "profile.attributes.personality.mediaFriendly.tooltip"},
		{label: "profile.attributes.personality.outspoken", value: "outspoken", tooltip: "profile.attributes.personality.outspoken.tooltip"},
		{label: "profile.attributes.personality.reserved", value: "reserved", tooltip: "profile.attributes.personality.reserved.tooltip"},
		{label: "profile.attributes.personality.shortTempered", value: "shortTempered", tooltip: "profile.attributes.personality.shortTempered.tooltip"},
		{label: "profile.attributes.personality.volatile", value: "volatile", tooltip: "profile.attributes.personality.volatile.tooltip"}
	]
};
