const singleFront = {
  headFace: { top: 3, left: 50 },
  neckCervicalSpine: { top: 11, left: 50 },
  sternumRibs: { top: 21, left: 50 },
  abdomen: { top: 35, left: 50 },
  elbowR: { top: 30, left: 26 },
  elbowL: { top: 30, left: 74 },
  lowerBackPelvisSacrum: { top: 43, left: 50 },
  shoulderR: { top: 16, left: 30 },
  shoulderL: { top: 16, left: 70 },
  armR: { top: 23, left: 30 },
  armL: { top: 23, left: 70 },
  forearmR: { top: 35, left: 22 },
  forearmL: { top: 35, left: 78 },
  wristR: { top: 40, left: 18 },
  wristL: { top: 40, left: 82 },
  handFingerThumbR: { top: 49, left: 12 },
  handFingerThumbL: { top: 49, left: 88 },
  thighR: { top: 53, left: 41 },
  thighL: { top: 53, left: 59 },
  kneeR: { top: 65, left: 41 },
  kneeL: { top: 65, left: 59 },
  shinR: { top: 75, left: 41 },
  shinL: { top: 75, left: 59 },
  ankleR: { top: 85, left: 41 },
  ankleL: { top: 85, left: 59 },
  footToeR: { top: 92, left: 35 },
  footToeL: { top: 92, left: 65 },
};

const singleBack = {
  upperback: { top: 21, left: 50 },
  lowerback: { top: 35, left: 50 },
  hamstringL: { top: 58, left: 40 },
  hamstringR: { top: 58, left: 60 },
  lowerLegAchillesTendonL: { top: 90, left: 40 },
  lowerLegAchillesTendonR: { top: 90, left: 60 },
};

export const singlePoints = {
  front: singleFront,
  back: singleBack,
};

export const fullPoints = {
  front: { ...singleFront },
  back: {
    ...singleBack,
    headFace: { top: 3, left: 50 },
    neckCervicalSpine: { top: 11, left: 50 },
    lowerBackPelvisSacrum: { top: 43, left: 50 },
    elbowL: { top: 30, left: 26 },
    elbowR: { top: 30, left: 74 },
    armL: { top: 23, left: 30 },
    armR: { top: 23, left: 70 },
    shoulderL: { top: 16, left: 30 },
    shoulderR: { top: 16, left: 70 },
    forearmL: { top: 35, left: 22 },
    forearmR: { top: 35, left: 78 },
    wristL: { top: 40, left: 18 },
    wristR: { top: 40, left: 82 },
    handFingerThumbL: { top: 49, left: 12 },
    handFingerThumbR: { top: 49, left: 88 },
    kneeL: { top: 65, left: 41 },
    kneeR: { top: 65, left: 59 },
    footToeL: { top: 92, left: 35 },
    footToeR: { top: 92, left: 65 },
  },
};
